### ISSUE TITLE
PostgreSQL 10.1 system incompatibility

### ISSUE THREAD

**Issue by pasichnichenko** [postgrespro/mamonsu#104]
PostgreSQL 10.1 does not have pg_catalog.pg_current_xlog_location()

> $ createdb mamonsu
$ createuser mamonsu
$ mamonsu bootstrap -U postgres -d mamonsu
Query:
CREATE OR REPLACE FUNCTION public.mamonsu_timestamp_master_update()
RETURNS void AS $$
  UPDATE public.mamonsu_timestamp_master_2_3_1 SET
    ts = extract(epoch from now() at time zone 'utc')::double precision,
    lsn = pg_catalog.pg_current_xlog_location()
  WHERE
    id = 1;
$$ LANGUAGE SQL SECURITY DEFINER;
error: (u'ERROR', u'ERROR', u'42883', u'function pg_catalog.pg_current_xlog_location() does not exist', u'No function matches the given name and argument types. You might need to add explicit type casts.', u'222', u'parse_func.c', u'528', u'ParseFuncOrColumn', u'', u'')
$

**Comment by pasichnichenko** [comment]
simple test for function presence in most recent pgsql 10.1:

> postgres=# select * from pg_catalog.pg_current_xlog_location();
> ERROR:  function pg_catalog.pg_current_xlog_location() does not exist
> LINE 1: select * from pg_catalog.pg_current_xlog_location();
>                       ^
> HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
> postgres=#

**Comment by casperr0** [comment]
исправлено в последней версии mamonsu
