### ISSUE TITLE
Debug плагина

### ISSUE THREAD

**Issue by osipkovandrey** [postgrespro/mamonsu#105]
Добрый день! Подскажите как запустить в debug свой плагин? пытался подключится к нему через pycharm но не получилось

**Comment by bot659** [comment]
Здравствуйте!
Подскажите, по какому принципу пишутся плагины? Я правильно понял, что скрипт должен быть на питоне и возвращать данные в json формате, понятному заббиксу (например zabbix trapper)?

**Comment by osipkovandrey** [comment]
Да все верно. Если в своем скрипте наследование идет от Plugin, то уже есть встроенный отправщик данных, которому передаете, название метрики, величину и время. Так же в скрипте задаете период отправки данных.

**Comment by bot659** [comment]
Отлично! Спасибо!

**Comment by casperr0** [comment]
если вы создали новый плагин и добавили его имя в /mamonsu/plugins/pgsql/__init__.py (если плагин для PG, например), то он должен отображатся при запуске в debug в логе (если вы установили в файле agent.conf log level на debug )
