### ISSUE TITLE
Unable to view data in Zabbix web ui

### ISSUE THREAD

**Issue by vfsoraki** [postgrespro/mamonsu#106]
I have installed mamonsu 2.3.2 using pip.

I also have Zabbix 3.4 installed.

I have done everything in readme but I can't see data in Zabbix ui.

This is mamonsu log:

> [DEBUG] 2018-01-16 12:40:30,109 - ZBX-192.168.56.120:10051	-	response: b'{"response":"success","info":"processed: 0; failed: 115; total: 115; seconds spent: 0.004268"}'
[ERROR] 2018-01-16 12:40:30,110 - ZBX-192.168.56.120:10051	-	On request:
{"request": "sender data", "data": [{"host": "arch-adtube", "key": "pgsql.autovacumm.count[]", "value": "0", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.discovery[]", "value": "{\"data\": [{\"{#DATABASE}\": \"postgres\"}, {\"{#DATABASE}\": \"js_test_dev\"}, {\"{#DATABASE}\": \"bidder_dev\"}, {\"{#DATABASE}\": \"bidder_test\"}, {\"{#DATABASE}\": \"adtube_api_dev\"}, {\"{#DATABASE}\": \"dsp_api_dev\"}, {\"{#DATABASE}\": \"dsp_api_test\"}, {\"{#DATABASE}\": \"ssp_api_dev\"}, {\"{#DATABASE}\": \"ssp_api_test\"}, {\"{#DATABASE}\": \"adtube_api_test\"}, {\"{#DATABASE}\": \"stats_test\"}, {\"{#DATABASE}\": \"domain_model_test\"}, {\"{#DATABASE}\": \"domain_model_dev\"}, {\"{#DATABASE}\": \"dsp_dev\"}, {\"{#DATABASE}\": \"ssp_dev\"}, {\"{#DATABASE}\": \"ssp_test\"}, {\"{#DATABASE}\": \"dsp_test\"}, {\"{#DATABASE}\": \"ssp_prod\"}, {\"{#DATABASE}\": \"stats_prod\"}, {\"{#DATABASE}\": \"dsp_prod\"}, {\"{#DATABASE}\": \"backend_platform_dev\"}, {\"{#DATABASE}\": \"backend_platform_test\"}, {\"{#DATABASE}\": \"backend_platform_prod\"}, {\"{#DATABASE}\": \"mamonsu\"}]}", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.bloating_tables[mamonsu]", "value": "0", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.max_age[mamonsu]", "value": "48376", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.size[mamonsu]", "value": "7338520", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.bloating_tables[backend_platform_prod]", "value": "0", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.max_age[backend_platform_prod]", "value": "48376", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.size[backend_platform_prod]", "value": "8411672", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.bloating_tables[backend_platform_test]", "value": "0", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.max_age[backend_platform_test]", "value": "48376", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.size[backend_platform_test]", "value": "8542744", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.bloating_tables[backend_platform_dev]", "value": "0", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.max_age[backend_platform_dev]", "value": "48376", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.size[backend_platform_dev]", "value": "8780312", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.bloating_tables[dsp_prod]", "value": "0", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.max_age[dsp_prod]", "value": "48376", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.size[dsp_prod]", "value": "7232024", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.bloating_tables[stats_prod]", "value": "0", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.max_age[stats_prod]", "value": "48376", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.size[stats_prod]", "value": "7297560", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.bloating_tables[ssp_prod]", "value": "0", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.max_age[ssp_prod]", "value": "48376", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.size[ssp_prod]", "value": "7469592", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.bloating_tables[dsp_test]", "value": "0", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.max_age[dsp_test]", "value": "48376", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.size[dsp_test]", "value": "7518744", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.bloating_tables[ssp_test]", "value": "0", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.max_age[ssp_test]", "value": "48376", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.size[ssp_test]", "value": "7617048", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.bloating_tables[ssp_dev]", "value": "0", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.max_age[ssp_dev]", "value": "48376", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.size[ssp_dev]", "value": "7535128", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.bloating_tables[dsp_dev]", "value": "0", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.max_age[dsp_dev]", "value": "48376", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.size[dsp_dev]", "value": "7428632", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.bloating_tables[domain_model_dev]", "value": "0", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.max_age[domain_model_dev]", "value": "48376", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.size[domain_model_dev]", "value": "7232024", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.bloating_tables[domain_model_test]", "value": "0", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.max_age[domain_model_test]", "value": "48376", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.size[domain_model_test]", "value": "7240216", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.bloating_tables[stats_test]", "value": "0", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.max_age[stats_test]", "value": "48376", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.size[stats_test]", "value": "7240216", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.bloating_tables[adtube_api_test]", "value": "0", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.max_age[adtube_api_test]", "value": "48376", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.size[adtube_api_test]", "value": "7240216", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.bloating_tables[ssp_api_test]", "value": "0", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.max_age[ssp_api_test]", "value": "48376", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.size[ssp_api_test]", "value": "7469592", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.bloating_tables[ssp_api_dev]", "value": "0", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.max_age[ssp_api_dev]", "value": "48376", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.size[ssp_api_dev]", "value": "7420440", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.bloating_tables[dsp_api_test]", "value": "0", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.max_age[dsp_api_test]", "value": "48376", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.size[dsp_api_test]", "value": "7420440", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.bloating_tables[dsp_api_dev]", "value": "0", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.max_age[dsp_api_dev]", "value": "48376", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.size[dsp_api_dev]", "value": "7412248", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.bloating_tables[adtube_api_dev]", "value": "0", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.max_age[adtube_api_dev]", "value": "48376", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.size[adtube_api_dev]", "value": "7240216", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.bloating_tables[bidder_test]", "value": "0", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.max_age[bidder_test]", "value": "48376", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.size[bidder_test]", "value": "7551512", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.bloating_tables[bidder_dev]", "value": "0", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.max_age[bidder_dev]", "value": "48376", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.size[bidder_dev]", "value": "7952920", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.bloating_tables[js_test_dev]", "value": "0", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.max_age[js_test_dev]", "value": "48376", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.size[js_test_dev]", "value": "7330328", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.bloating_tables[postgres]", "value": "0", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.max_age[postgres]", "value": "48376", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.database.size[postgres]", "value": "7232024", "clock": 1516093821}, {"host": "arch-adtube", "key": "pgsql.buffers[dirty]", "value": "8192", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.buffers[twice_used]", "value": "37675008", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.buffers[size]", "value": "134217728", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.oldest[query_time]", "value": "0.0", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.oldest[xid_age]", "value": "0", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.wal.count[]", "value": "2", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.wal.write[]", "value": "2.0", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.tuples[updated]", "value": "0.016666666666666666", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.tuples[returned]", "value": "434.06666666666666", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.tuples[inserted]", "value": "0.0", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.tuples[fetched]", "value": "4.6", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.tuples[deleted]", "value": "0.0", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.temp[files]", "value": "0.0", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.temp[bytes]", "value": "0.0", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.events[xact_rollback]", "value": "0.0", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.events[deadlocks]", "value": "0.0", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.events[conflicts]", "value": "0.0", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.blocks[read]", "value": "0.0", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.blocks[hit]", "value": "28.866666666666667", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.transactions[total]", "value": "1.1166666666666667", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.cache[hit]", "value": "99", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.uptime[]", "value": "270883", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.ping[]", "value": "0.7406949996948242", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.bgwriter[buffers_alloc]", "value": "0.0", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.bgwriter[buffers_backend_fsync]", "value": "0.0", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.bgwriter[buffers_backend]", "value": "0.0", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.bgwriter[maxwritten_clean]", "value": "0.0", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.bgwriter[buffers_clean]", "value": "0.0", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.bgwriter[buffers_checkpoint]", "value": "0.0", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.connections[total]", "value": "34", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.connections[idle_in_transaction]", "value": "0.0", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.connections[idle]", "value": "23.0", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.connections[active]", "value": "1.0", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.pg_locks[accessexclusive]", "value": "0", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.pg_locks[exclusive]", "value": "1", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.pg_locks[sharerowexclusive]", "value": "0", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.pg_locks[share]", "value": "0", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.pg_locks[shareupdateexclusive]", "value": "0", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.pg_locks[rowexclusive]", "value": "0", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.pg_locks[rowshare]", "value": "0", "clock": 1516093820}, {"host": "arch-adtube", "key": "pgsql.pg_locks[accessshare]", "value": "1", "clock": 1516093820}], "clock": 1516093830}
get response with failed items:
b'{"response":"success","info":"processed: 0; failed: 115; total: 115; seconds spent: 0.004268"}'

Any idea why it might not be sending data to Zabbix?

**Comment by vadv** [comment]
Сheck that the zabbix template is attached to the host "arch-adtube":

```
get response with failed items:
b'{"response":"success","info":"processed: 0; failed: 115; total: 115; seconds spent: 0.004268"}'
```

**Comment by vfsoraki** [comment]
![deepinscreenshot_select-area_20180116141832](https://user-images.githubusercontent.com/7745247/34984935-b9f39dae-fac7-11e7-8301-0aef3ae0b10a.png)

It is.

**Comment by vfsoraki** [comment]
Sorry I found the error. The host name was `Arch` not `arch-adtube`. How silly of me!

Thanks!
