### ISSUE TITLE
Manonsu error

### ISSUE THREAD

**Issue by edib** [postgrespro/mamonsu#108]
I am getting these messages on master and replicas randomly. It seems everything is ok on the servers. 
Any idea why that is happening?
> plugin errors (mypostgres:mamonsu.plugin.errors[]): Last: catch error: (u'ERROR', u'ERROR', u'57014', u'canceling statement due to statement timeout', u'postgres.c', u'2956', u'ProcessInterrupts', u'', u''). Total count: 18.

**Comment by nikolaev-rd** [comment]
have the same issue

**Comment by nikolaev-rd** [comment]
As workaround you can change [`query_timeout`](https://github.com/postgrespro/mamonsu/blob/master/packaging/conf/example.conf#L13)
