### ISSUE TITLE
Ошибки в логе после обнволения zabbix, mamonsu

### ISSUE THREAD

**Issue by ktulkhu** [postgrespro/mamonsu#109]
Добрый день. 
После yum update обновился как zabbix (3.4.8), так и mamonsu (2.3.4). 
Мониторинг mamonsu подключен на сам zabbix-сервер, так как там pgsql вертится. 

В логах теперь постоянно одни и те же ошибки: 

[ERROR] 2018-04-09 16:32:54,916 - XLOG  -       catch error: (u'ERROR', u'ERROR', u'42501', u'permission denied for relation mamonsu_config', u'aclchk.c', u'3411', u'acl
check_error', u'', u'')
[INFO] 2018-04-09 16:32:54,917 - XLOG   -       hint: enable debug level to full exception trace

[INFO] 2018-04-09 16:33:04,019 - CONNECTIONS    -       started ...
[ERROR] 2018-04-09 16:33:04,020 - CONNECTIONS   -       catch error: (u'ERROR', u'ERROR', u'42883', u'function mamonsu_get_connections_states() does not exist', u'No function matches the given name and argument types. You might need to add explicit type casts.', u'29', u'parse_func.c', u'523', u'ParseFuncOrColumn', u'', u'')
[INFO] 2018-04-09 16:33:04,020 - CONNECTIONS    -       hint: enable debug level to full exception trace

[INFO] 2018-04-09 16:33:04,026 - OLDEST -       started ...
[ERROR] 2018-04-09 16:33:04,136 - OLDEST        -       catch error: (u'ERROR', u'ERROR', u'42883', u'function public.mamonsu_get_oldest_xid() does not exist', u'No function matches the given name and argument types. You might need to add explicit type casts.', u'9', u'parse_func.c', u'523', u'ParseFuncOrColumn', u'', u'')
[INFO] 2018-04-09 16:33:04,137 - OLDEST -       hint: enable debug level to full exception trace

Подскажите, куда копать, что крутить?

**Comment by ktulkhu** [comment]
Затрудняюсь сказать точно, но, по-моему 2.3.0.

**Comment by gsmol** [comment]
bootstrap заново делали?

**Comment by ktulkhu** [comment]
Нет, не делал, даже не думал в эту сторону. Я в этом не сильно разбираюсь, думал он делается единожды, при установке.

**Comment by gsmol** [comment]
bootstrap решит вашу проблему.
Проблема в том, что mamonsu должен проверять версию bootstrap`а и не должен пытаться использовать ф-ции, которых нет в существующей версии bootstrap`а.
Не исключено, что в этой проверка есть ошибка.
Попробую воспроизвести.

**Comment by gsmol** [comment]
Да, обязателен, документацию поправим.
