### ISSUE TITLE
`mamonsu bootstrap` errors [Ru-Ru]

### ISSUE THREAD

**Issue by TEH30P** [postgrespro/mamonsu#112]
*Ну я так понимаю, по русски меня поймуть.*
## Выполняю команду
~~~ bash
mamonsu bootstrap -U postgres -d mamonsu --host localhost -M mamonsu
~~~
ответ  такой:
~~~
Query:
CREATE EXTENSION IF NOT EXISTS pg_buffercache;
error: (u'ERROR', u'ERROR', u'58P01', u'could not open extension control file "/usr/pgsql-10/share/extension/pg_buffercache.control": No such file or directory', u'extension.c', u'494', u'parse_extension_control_file', u'', u'')
bash-4.2$ mamonsu bootstrap -U postgres -d mamonsu --host localhost -M mamonsu
~~~
Пробовал через `su postgres` и через `sudo -s` - результат один.
Плюс в `/var/log/mamonsu/agent.log` вот такие сообщения:
~~~
[INFO] 2018-09-03 14:16:06,128 - HEALTH -       === Keep alive ===
[INFO] 2018-09-03 14:16:06,215 - PGSQL-(host=localhost db=postgres user=postgres port=5432)     -       Found mamonsu bootstrap
[INFO] 2018-09-03 14:17:05,624 - PGBUFFERCACHE  -       Extension 'pg_buffercache' is not installed
[INFO] 2018-09-03 14:17:05,825 - PGSTATSTATEMENT        -       Extension 'pg_stat_statements' is not installed
[INFO] 2018-09-03 14:18:06,402 - PGSQL-(host=localhost db=postgres user=postgres port=5432)     -       Found mamonsu bootstrap
[INFO] 2018-09-03 14:20:06,691 - PGSQL-(host=localhost db=postgres user=postgres port=5432)     -       Found mamonsu bootstrap
[INFO] 2018-09-03 14:22:06,861 - PGSQL-(host=localhost db=postgres user=postgres port=5432)     -       Found mamonsu bootstrap
[INFO] 2018-09-03 14:23:06,143 - PGBUFFERCACHE  -       Extension 'pg_buffercache' is not installed
[INFO] 2018-09-03 14:23:06,343 - PGSTATSTATEMENT        -       Extension 'pg_stat_statements' is not installed
[INFO] 2018-09-03 14:24:07,041 - PGSQL-(host=localhost db=postgres user=postgres port=5432)     -       Found mamonsu bootstrap
~~~

Пользователя и БД делал так:
~~~ bash
/usr/pgsql-10/bin/createuser --pwprompt mamonsu 
/usr/pgsql-10/bin/createdb -O mamonsu mamonsu
~~~

Я не против дать роли mamonsu права superuser, вы только объясните:
* зачем права superuser если в конфиге у меня прописана роль postgres. и агент заходит под postgres?
* более того mamonsu заработал и до того как я сделал `mamonsu bootstrap`, причём `mamonsu agent metric-get ` работали (правда все не проверял).
* этот `bootstrap` он что делает ? 
* `bootstrap` нужен, при моих настройках (см ниже)?  он нужен если я дам роли mamonsu права superuser?
* просто к бд есть подключение с mamonsu демона.

## Система
~~~ bash
➜ cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core) 
➜ psql -U postgres -c 'SELECT version();'
                                                 version
---------------------------------------------------------------------------------------------------------
 PostgreSQL 10.4 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28), 64-bit
~~~ 
mamonsu 2.3.4 (не знаю как посмотреть, но ставил я его)

~~~ bash
➜  cat /etc/mamonsu/agent.conf
[postgres]
enabled = True
user = postgres
password = None
database = postgres
host = localhost
;host = /tmp/.s.PGSQL.5432
port = 5432
application_name = mamonsu
query_timeout = 10

[system]
enabled = True

[sender]
queue = 2048

[agent]
enabled = True
host = 127.0.0.1
port = 10052

[plugins]
enabled = False
directory = /etc/mamonsu/plugins

[zabbix]
enabled = True
client = zbx-01-msk
;client = zbx-01-msk.inner.alfaleasing.ru
address = 127.0.0.1
port = 10051


[metric_log]
enabled = False
directory = /var/log/mamonsu
max_size_mb = 1024

[log]
file = /var/log/mamonsu/agent.log
level = INFO
format = [%(levelname)s] %(asctime)s - %(name)s -       %(message)s

[health]
max_memory_usage = 41943040

[databases]
bloat_scale = 0.2
min_rows = 50

[pghealth]
uptime = 600
cache = 80

[xlog]
lag_more_then_in_sec = 300

[checkpoint]
max_checkpoint_by_wal_in_hour = 12

[oldest]
max_xid_age = 18000000
max_query_time = 18000

[cfs]
force_enable = False

[disksizes]
vfs_percent_free = 10
vfs_inode_percent_free = 10

[systemuptime]
uptime = 300
~~~

~~~ bash
➜  cat /var/lib/pgsql/10/data/pg_hba.conf 
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     trust
# IPv4 local connections:
host    all             all             127.0.0.1/32            trust
# IPv6 local connections:
host    all             all             ::1/128                 trust
# IPv4 remote connections:
host    all             all             192.168.0.0/16          md5
# IPv6 remote connections:
host    all             all             ::0/0                   md5
# Allow replication connections from localhost, by a user with the
# replication privilege.
local   replication     all                                     trust
host    replication     all             127.0.0.1/32            trust
host    replication     all             ::1/128                 trust

**Comment by casperr0** [comment]
ошибка возникает из-за того, что не установлен пакет postgresql-contrib и поэтому не создается расширение pg_buffercache. 
bootstrap нужен для запуска мониторинга без прав superuser. если bootstrap не уставновлен, то mamonsu будет работать c superuser rights.

**Comment by sanstepan** [comment]
root@jirabus:~# dpkg -l postgrespro*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                          Version         Architecture Description
+++-=============================-===============-============-============================================================
ii  postgrespro-ent-12-client     12.5.1-1.buster amd64        front-end programs for Postgres Pro Enterprise 12
ii  postgrespro-ent-12-contrib    12.5.1-1.buster amd64        additional facilities for Postgres Pro Enterprise 12
ii  postgrespro-ent-12-dev        12.5.1-1.buster amd64        development files for Postgres Pro Enterprise 12 programming
un  postgrespro-ent-12-docs       <none>          <none>       (no description available)
un  postgrespro-ent-12-docs-ru    <none>          <none>       (no description available)
ii  postgrespro-ent-12-libs:amd64 12.5.1-1.buster amd64        PostgresPro C client and ECPG libraries
ii  postgrespro-ent-12-plperl     12.5.1-1.buster amd64        PL/Perl procedural language for PostgresPro Enterprise 12
ii  postgrespro-ent-12-server     12.5.1-1.buster amd64        object-relational SQL database, version 12 server
root@jirabus:~# dpkg -l mamonsu
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version        Architecture Description
+++-==============-==============-============-=================================
ii  mamonsu        3.0.0-1.buster all          Monitoring agent for PostgreSQL
root@jirabus:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
root@jirabus:~# su - postgres -c "psql mamonsu"
psql (12.5)
Type "help" for help.

mamonsu=# \dx
                                     List of installed extensions
        Name        | Version |   Schema   |                        Description
--------------------+---------+------------+-----------------------------------------------------------
 amcheck            | 1.2     | public     | functions for verifying relation integrity
 pg_buffercache     | 1.3     | public     | examine the shared buffer cache
 pg_query_state     | 1.1     | public     | tool for inspection query progress
 pg_stat_statements | 1.7     | public     | track execution statistics of all SQL statements executed
 pg_wait_sampling   | 1.1     | public     | sampling based statistics of wait events
 plpgsql            | 1.0     | pg_catalog | PL/pgSQL procedural language
(6 rows)

И тем не менее в логе ошибка:
[INFO] 2021-11-08 11:50:40,331 - PGBUFFERCACHE	-	started ...
[INFO] 2021-11-08 11:50:40,333 - PGSQL-(host=localhost db=mamonsu user=mamonsu port=5432)	-	connecting
[INFO] 2021-11-08 11:50:40,341 - PGSQL-(host=localhost db=mamonsu user=mamonsu port=5432)	-	connected
[ERROR] 2021-11-08 11:50:40,344 - PGBUFFERCACHE	-	catch error: {'S': 'ERROR', 'V': 'ERROR', 'C': '42883', 'M': 'function mamonsu.buffer_cache() does not exist', 'H': 'No function matches the given name and argument types. You might need to add explicit type casts.', 'P': '37', 'F': 'parse_func.c', 'L': '631', 'R': 'ParseFuncOrColumn'}
[INFO] 2021-11-08 11:50:40,344 - PGBUFFERCACHE	-	hint: enable debug level to full exception trace
[INFO] 2021-11-08 11:50:40,377 - PGSQL-(host=localhost db=mamonsu user=mamonsu port=5432)	-	connecting
[INFO] 2021-11-08 11:50:40,383 - PGSQL-(host=localhost db=mamonsu user=mamonsu port=5432)	-	connected
[INFO] 2021-11-08 11:50:40,487 - PGSQL-(host=localhost db=mamonsu user=mamonsu port=5432)	-	Found mamonsu bootstrap

**Comment by cuprumtan** [comment]
@sanstepan эта ошибка в версии 3.0 была связана с переносом всех объектов mamonsu в отдельную схему - изначально не учитывалось, что `pg_buffercache` уже может стоять в другой схеме. В версии [3.1](https://github.com/postgrespro/mamonsu/releases/tag/3.1.0) баг исправлен.
Для версии 3.0 решением будет смена сандартной схемы `pg_buffercache` на `mamonsu` и повторный запуск bootstrap:
```
ALTER EXTENSION pg_buffercache SET SCHEMA mamonsu;
```
Повторный запуск bootstrap пройдет с ошибкой, но при этом должны создаться все объекты для работы с этим расширением
```
root@home:~# mamonsu bootstrap -U postgres -d mamonsu_test_db -x
2021-11-08 12:14:51.231 MSK [17787] ERROR:  extension "pg_buffercache" already exists
2021-11-08 12:14:51.231 MSK [17787] STATEMENT:  
	CREATE EXTENSION pg_buffercache WITH SCHEMA mamonsu;
	
Bootstrap failed to create pg_buffercache extension.
Error: {'S': 'ERROR', 'V': 'ERROR', 'C': '42710', 'M': 'extension "pg_buffercache" already exists', 'F': 'extension.c', 'L': '1803', 'R': 'CreateExtension'}
Please install pg_buffercache extension and rerun bootstrap if you want to get metrics from pg_buffercache view. 
Bootstrap successfully completed
```
```
mamonsu_test_db=# \df mamonsu.buffer*
                                             List of functions
 Schema  |     Name     |                  Result data type                   | Argument data types | Type 
---------+--------------+-----------------------------------------------------+---------------------+------
 mamonsu | buffer_cache | TABLE(size bigint, twice_used bigint, dirty bigint) |                     | func
(1 row)

```
