### ISSUE TITLE
Проблема при обновлении mamonsu и postgres

### ISSUE THREAD

**Issue by ktulkhu** [postgrespro/mamonsu#116]
Добрый день. 
Обновил сейчас скопом пакеты на Linux CentOS 7.5, в том числе обновился PostgreSQL
для мониторинга PostgreSQL использую mamonsu
после обновления сыплются ошибки как в логе постгри, так и мамонсу:

[INFO] 2018-11-04 19:56:41,161 - CONNECTIONS - started ...
[ERROR] 2018-11-04 19:56:41,171 - CONNECTIONS - catch error: (u'ERROR', u'3F000', u'schema "mamonsu" does not exist', u'namespace.c', u'2870', u'
get_namespace_oid', u'', u'')
[INFO] 2018-11-04 19:56:41,171 - CONNECTIONS - hint: enable debug level to full exception trace
[INFO] 2018-11-04 19:56:51,172 - CONNECTIONS - started ...

при этом сама база mamonsu живая вроде. Таблички в ней есть, все такое.

было: 
---------------------------
cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)

psql -U postgres -c 'SELECT version();'
                                                    version
----------------------------------------------------------------------------------------------------------------
PostgreSQL 9.4.12 on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11), 64-bit

mamonsu agent version
2.3.0

стало:
---------------------------
cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)

psql -U postgres -c 'SELECT version();'
version
---------------------------------------------------------------------------------------------------------------
PostgreSQL 9.4.19 on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4), 64-bit

mamonsu agent version
2.3.4

Пересоздавать bootstrap пробовал. 
Проблема в какой-то совместимости новых версий?

**Comment by ktulkhu** [comment]
Проект перестал поддерживаться?

**Comment by casperr0** [comment]
проблемы совместимости версий быть не должно. если пересоздание bootstap так и не помогло, то измените в файле agent.conf log level на debug и посмотреть в логе при каком запросе возникает эта ошибка.
