### ISSUE TITLE
429 Too Many Requests On packagecloud

### ISSUE THREAD

**Issue by dan-aksenov** [postgrespro/mamonsu#118]
Got "429 Too Many Requests" while trying to install/update mamonsu package from packagecloud.
Seems that bandwidth limit on packagecloud.io is reached.
Any chance to fix this?

**Comment by womchik** [comment]
I got this error too

**Comment by tanertas** [comment]
Any news on this?
https://packagecloud.io/postgrespro/mamonsu/debian/dists/buster says:
**Bandwidth or Storage Limit Exceeded**

**Comment by casperr0** [comment]
We know about problems with packagecloud. New packages will be available from new repository soon. We are sorry for the inconvenience with packages

**Comment by casperr0** [comment]
The new repo for packages is already available https://github.com/postgrespro/mamonsu#installation
