### ISSUE TITLE
Работа с mamonsu через zabbix proxy

### ISSUE THREAD

**Issue by olegkudrin** [postgrespro/mamonsu#119]
Возможна ли работа с mamonsu через zabbix proxy? У меня не получилось.

**Comment by dan-aksenov** [comment]
У меня работает через пассивную прокси. С активной не проверял.

**Comment by proffust** [comment]
> Возможна ли работа с mamonsu через zabbix proxy? У меня не получилось.

возможна, надо указать адрес прокси в настройках и все
