### ISSUE TITLE
pgsql.connections[waiting] не собирается в версиях новее 9.5

### ISSUE THREAD

**Issue by triwada** [postgrespro/mamonsu#120]
Начиная с версии 9.6 в pg_stat_activity нет столбца waiting, поэтому не отрабатывает сбор метрики pgsql.connections[waiting]. 

mamonsu/plugins/pgsql/connections.py
...
```
		if Pooler.server_version_less('9.5.0'):
			if Pooler.is_bootstraped() and Pooler.bootstrap_version_greater('2.3.4'):
				result = Pooler.query(
					'select count(*) '
					'from mamonsu.mamonsu_get_connections_states() '
					'where waiting')
			else:
				result = Pooler.query(
					'select count(*) '
					'from pg_catalog.pg_stat_activity where waiting')
			zbx.send('pgsql.connections[waiting]', int(result[0][0]))
```

По идее для новых версий можно заменить на

`select count(*) from pg_catalog.pg_stat_activity where wait_event is not NULL`

**Comment by popov83** [comment]
Проверьте пожалуйста в последней версии.
Это было исправлено
