### ISSUE TITLE
при вызове mamonsu_buffer_cache() создаются временные файлы

### ISSUE THREAD

**Issue by triwada** [postgrespro/mamonsu#121]
На кластере с shared_buffers = 16 ГБ выполнение запроса приводит к формированию временных файлов размером 40 МБ, запрос выполняется около 1.3 мс
SELECT size, twice_used, dirty FROM public.mamonsu_buffer_cache ();

Такое поведение наблюдается на двух кластерах с версией PostgreSQL 9.6.11 и 10.6.2 с shared_buffers = 16 ГБ, work_mem = 8 МБ.

**Comment by tarabanton** [comment]
Наблюдали аналогичное. Результат выполнения изначальной функции (а там ВСЕ секции shared memory) не влезает у вас в work_mem и потому пишется во временные файлы. У нас с shared_buffers = 32GB результат занимает больше 100 мегабайт.

IMHO not a bug

**Comment by finnhuman** [comment]
Проблема особенно актуальна для серверов с объемами shared_buffers в десятки и сотни GB. К примеру для shared_buffers = 125GB размер временного файла достигает 600MB. Есть ли  параметр, указывающий mamonsu размер work_mem для его сессии?

**Comment by sgrinko** [comment]
Если вы используете bootstrap (БД mamonsu) то у вас есть возможность указать в настройках функции public.mamonsu_buffer_cache() параметр work_mem с нужным значением памяти. К примеру для shared_buffers = 32 Гб потребуется 400MB
```
ALTER FUNCTION public.mamonsu_buffer_cache() SET work_mem='300MB';
```

**Comment by finnhuman** [comment]
@sgrinko спасибо!

**Comment by glosha** [comment]
Подскажите, а можно в мамонсу отключить сбор именной  этой метрики - mamonsu_buffer_cache() ?

**Comment by popov83** [comment]
да, добавьте в файл /etc/mamonsu/agent.conf в раздел [pgbuffercache] строку enabled = False
[pgbuffercache]
enabled = False
