### ISSUE TITLE
Error при создании template файла и наличии плагина

### ISSUE THREAD

**Issue by sgrinko** [postgrespro/mamonsu#122]
Создал плагин для pgbouncer.
Пробую выполнить создание шаблона и получаю ошибку:
В коде плагина нет русских букв. Код плагина приложил.
```
mamonsu export template template.xml --add-plugins /etc/mamonsu/plugins
Traceback (most recent call last):
  File "/bin/mamonsu", line 9, in <module>
    load_entry_point('mamonsu==2.3.4', 'console_scripts', 'mamonsu')()
  File "/usr/lib/python2.7/site-packages/mamonsu/lib/runner.py", line 67, in start
    f.write(template.xml(plugins))
  File "/usr/lib/python2.7/site-packages/mamonsu/lib/zbx_template.py", line 116, in xml
    return self.mainTemplate.format(**template_data)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 33600: ordinal not in range(128)
```
[pgbouncer.zip](https://github.com/postgrespro/mamonsu/files/2959947/pgbouncer.zip)

Использую последнюю версию mamonsu
```
# mamonsu --version
mamonsu 2.3.4
```

**Comment by sgrinko** [comment]
я всё же обнаружил русский текст у себя :(
если его заменить на английский, то всё хорошо.
Поэтому встречное предложение - нужно добавить возможность использования русского текста в плагинах.

**Comment by sgrinko** [comment]
я всё же обнаружил русский текст у себя :(
если его заменить на английский, то всё хорошо.
Поэтому встречное предложение - нужно добавить возможность использования русского текста в плагинах.

**Comment by popov83** [comment]
Поддержку русских букв включать не будем.

**Comment by sgrinko** [comment]
Почему? В чём причина?
