### ISSUE TITLE
Неправильная версия deb пакета

### ISSUE THREAD

**Issue by proffust** [postgrespro/mamonsu#132]
Собираю пакеты по инструкции, но на выходе получаю deb пакет с неправильной версией
root@denis:/home/proff/mamonsu/build/mamonsu-2.4.0# dpkg -l | grep mamonsu
ii  mamonsu                                  2.3.4-1                                             all          Monitoring agent for PostgreSQL
root@denis:/home/proff/mamonsu/build/mamonsu-2.4.0# mamonsu --version
mamonsu 2.4.0
лог сборки
https://pastebin.com/5D6vGcQe

**Comment by casperr0** [comment]
проблема должна быть решена в новой версии 2.4.1

**Comment by proffust** [comment]
все ок
dpkg -l | grep mamonsu
ii  mamonsu 2.4.1-1 all Monitoring agent for PostgreSQL
mamonsu --version
mamonsu 2.4.1
