### ISSUE TITLE
template export error

### ISSUE THREAD

**Issue by stepansantalov** [postgrespro/mamonsu#134]
На новом заббиксе (4.4) ошибка экспорта (почему, кстати, экспорт, это же импорт?):
root@database:~# mamonsu zabbix template export template.xml --url=http://zabbix.server/ --user=Admin --password=******
Template export error: Error response from zabbix api: {
  "message": "Application error.", 
  "code": -32500, 
  "data": "Invalid tag \"/zabbix_export/templates/template(1)/items/item(1)\": the tag \"logtimefmt\" is missing."
}

mamonsu version mamonsu 2.3.4

**Comment by casperr0** [comment]
We will add zabbix-server 4.4 support in the next release

**Comment by alexeyshishkin01** [comment]
same issue with

mamonsu --version
mamonsu 2.4.1

**Comment by casperr0** [comment]
The problem is fixed in version 2.4.3

**Comment by proea** [comment]
The same issue in 
mamonsu 2.4.5
zabbix 5.0.1

**Comment by popov83** [comment]
@proea

**Comment by popov83** [comment]
@proea  show the error.  What command do you use?

**Comment by proea** [comment]
@popov83 
I used the import template from the XML file feature in zabbix ui

![image](https://user-images.githubusercontent.com/2929968/85137309-a6433300-b249-11ea-9ce3-27c8da8eac6f.png)

Template was obtained from `mamonsu export template template.xml --add-plugins /etc/mamonsu/plugins`

This one has the same error: https://postgrespro.ru/media/2019/09/13/template.xml

**Comment by popov83** [comment]
what plugins in the directory /etc/mamonsu/plugins ? Please, attach here.

**Comment by proea** [comment]
@popov83 I have no plugins there

**Comment by popov83** [comment]
Please, attach here the template. Try to export to zabbix the file 
[template_for_zabbix5.xml.txt](https://github.com/postgrespro/mamonsu/files/4805233/template_for_zabbix5.xml.txt)

**Comment by proea** [comment]
Your file: ![image](https://user-images.githubusercontent.com/2929968/85921472-3d7d3b80-b885-11ea-8aaf-a190f5196b88.png)

A template that was exported from mamonsu: [template.xml.txt](https://github.com/postgrespro/mamonsu/files/4840443/template.xml.txt)

**Comment by casperr0** [comment]
Hello
Please try this template https://github.com/postgrespro/mamonsu/blob/master/packaging/conf/template.xml 
I have zabbix server 5.0.1 and it works for me fine

The template that you attached doesn't work for me either. Did your exported it using the command below:
`mamonsu export template template.xml --add-plugins /etc/mamonsu/plugins`
