### ISSUE TITLE
Предлагаю перейти на кодовую базу 3-й версии питона

### ISSUE THREAD

**Issue by sgrinko** [postgrespro/mamonsu#138]
Плюсы:
- уйдёт большая часть кода отвечающая за совместимость
- существенно станет легче внедрить поддержку юникода
- наверное много ещё чего...

возможный минус:
- наверное есть старые сборки linux для которых нет 3-й версии (надеюсь я ошибаюсь)

**Comment by casperr0** [comment]
Спасибо  за issue.
Да, переходить на 3-ю версию надо. 
Мы постараемся это сделать в одной их следующих версий

**Comment by casperr0** [comment]
В новой версии - mamonsu 2.5.1 - перешли на кодовую базу 3-й версии python

**Comment by sgrinko** [comment]
Спасибо!
