### ISSUE TITLE
недоступен repomd.xml для centos 7

### ISSUE THREAD

**Issue by barazbay** [postgrespro/mamonsu#139]
`https://repo.postgrespro.ru/mamonsu/latest/rpm/centos-7Server/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.

 One of the configured repositories failed (Mamonsu Packages for Red Hat Linux derivatives),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=pg_probackup ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable pg_probackup
        or
            subscription-manager repos --disable=pg_probackup

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=pg_probackup.skip_if_unavailable=true

failure: repodata/repomd.xml from pg_probackup: [Errno 256] No more mirrors to try.
https://repo.postgrespro.ru/mamonsu/latest/rpm/centos-7Server/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
`

**Comment by gsmol** [comment]
Добрый день!
Что возвращает ` cat /etc/os-release` ?
