### ISSUE TITLE
в репозитарии CentOS 7 нет новой версии 2.4.4

### ISSUE THREAD

**Issue by sgrinko** [postgrespro/mamonsu#140]
использую CentOS 7
```
# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
использую репозитарий:
http://repo.postgrespro.ru/mamonsu/latest/rpm/centos-7/

но там только версия mamonsu-2.4.2-1.el7.noarch.rpm

а как насчет новой версии 2.4.4 ?

**Comment by casperr0** [comment]
Добрый день
Постараемся добавить пакеты для новой версии в репозиторий в ближайшее время

**Comment by sgrinko** [comment]
Спасибо Даша!
Очень жду!

**Comment by sgrinko** [comment]
Даша, когда можно ожидать пакет новой версии ?

**Comment by casperr0** [comment]
Добрый день
По техническим причинам новые пакеты можно ожидать только к началу мая

**Comment by sgrinko** [comment]
Спасибо Даша! Очень ждём

**Comment by sgrinko** [comment]
Даша, какие новости ?

**Comment by casperr0** [comment]
Добрый день!
Прошу прощения за такую задержку с выпусками пакетов.
Мы выпустили новую версию и для нее доступны пакеты в репозитории : https://repo.postgrespro.ru/mamonsu/latest/rpm

**Comment by sgrinko** [comment]
Спасибо!
