### ISSUE TITLE
на главной странице в README нет в списке новых метрик

### ISSUE THREAD

**Issue by barazbay** [postgrespro/mamonsu#141]
список метрик, которые я нашел, возможно, список не полный
PostgreSQL: shared buffer dirty size 
PostgreSQL: shared buffer twice used size
PostgreSQL: shared buffer size
--

**Comment by casperr0** [comment]
Спасибо!
Исправили : https://github.com/postgrespro/mamonsu/commit/60dd239f73ef885ec083930f0e39729b345617f3
