### ISSUE TITLE
Sending metrics to multiple servers

### ISSUE THREAD

**Issue by Bexilit** [postgrespro/mamonsu#144]
Hello again!
Can we somehow send metrics to multiple servers using the mamonsu agent (as the standard Zabbix agent can do)? We usually use 3 Zabbix servers, but mamonsu can only send metrics to one, so we had to give it up.
But we want to go back to mamonsu )

**Comment by casperr0** [comment]
Hello!
Thank you for your interest in our project. 
For now,  I'm not aware of a workaround  for multiple Zabbix servers

**Comment by proffust** [comment]
такая возможность очень нужна, для обеспечения отказоустойчивости, или для отправки данных в разные заббиксы

**Comment by proffust** [comment]
Any updates?

**Comment by casperr0** [comment]
Hello
For now, we are not planning to add this feature to mamonsu
Although, you can check out Zabbix Agent 2 plugin for PostgreSQL monitoring which has this feature
