### ISSUE TITLE
issue on installing?

### ISSUE THREAD

**Issue by killmasta93** [postgrespro/mamonsu#145]
Hi,
Currently trying to install on my zabbix server to monitor postgresql, i check on the discovery i see unsupported key 

on the server i check the service

```
root@postgre:~# service mamonsu status
● mamonsu.service - LSB: Start mamonsu daemon
   Loaded: loaded (/etc/init.d/mamonsu; generated)
   Active: active (exited) since Sat 2020-08-01 19:29:54 -05; 37s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 14982 ExecStop=/etc/init.d/mamonsu stop (code=exited, status=0/SUCCESS)
  Process: 14995 ExecStart=/etc/init.d/mamonsu start (code=exited, status=0/SUCCESS)

Aug 01 19:30:15 postgre mamonsu[14995]: [INFO] 2020-08-01 19:30:15,271 - INSTANCE        -        started ...
Aug 01 19:30:15 postgre mamonsu[14995]: [ERROR] 2020-08-01 19:30:15,284 - INSTANCE        -        catch error: int() argument must be a string or a number, not 'NoneType'
Aug 01 19:30:15 postgre mamonsu[14995]: [INFO] 2020-08-01 19:30:15,284 - INSTANCE        -        hint: enable debug level to full exception trace
Aug 01 19:30:25 postgre mamonsu[14995]: [ERROR] 2020-08-01 19:30:25,274 - ZBX-127.0.0.1:10051        -        On request:
Aug 01 19:30:25 postgre mamonsu[14995]: {"data": [{"host": "localhost", "value": "35.0", "key": "pgsql.tuples[updated]", "clock": 1596328215}, {"host": "localhost", "value": "3855.5", "key": "pgsql.tuples[returned]", "clock": 159632821
Aug 01 19:30:25 postgre mamonsu[14995]: get response with failed items:
Aug 01 19:30:25 postgre mamonsu[14995]: {"response":"success","info":"processed: 0; failed: 13; total: 13; seconds spent: 0.000236"}
Aug 01 19:30:25 postgre mamonsu[14995]: [INFO] 2020-08-01 19:30:25,283 - INSTANCE        -        started ...
Aug 01 19:30:25 postgre mamonsu[14995]: [ERROR] 2020-08-01 19:30:25,297 - INSTANCE        -        catch error: int() argument must be a string or a number, not 'NoneType'
Aug 01 19:30:25 postgre mamonsu[14995]: [INFO] 2020-08-01 19:30:25,297 - INSTANCE        -        hint: enable debug level to full exception trace

```
The steps i took

```
echo "deb [arch=amd64] https://repo.postgrespro.ru/mamonsu/latest/deb/ $(lsb_release -cs) main-$(lsb_release -cs)" > /etc/apt/sources.list.d/mamonsu.list
 wget -O - https://repo.postgrespro.ru/mamonsu/keys/GPG-KEY-MAMONSU | sudo apt-key add - && sudo apt-get update
  sudo apt-get install mamonsu
  mamonsu export config /etc/mamonsu/agent.conf --add-plugins /etc/mamonsu/plugins
```
the part of the config

```
[postgres]
enabled = True
user = zabbix
password = mypassword
database = zabbix
host = localhost
port = 5432
application_name = mamonsu
query_timeout = 10

[system]
enabled = True

[sender]
queue = 2048

[agent]
enabled = True
host = 127.0.0.1
port = 10052

[plugins]
enabled = False
directory = /etc/mamonsu/plugins

[zabbix]
enabled = True
client = localhost
address = 127.0.0.1
port = 10051

```

Thank you

**Comment by casperr0** [comment]
Hello!
Have you created a host for mamonsu on Zabbix Server and attached mamonsu template to it?
Host name for mamonsu should be specified in the config file in section [zabbix] as "client". Looking at your config you have:
`client = localhost`
Do you have a host on Zabbix Server named "localhost" to which you have attached template for mamonsu?

**Comment by killmasta93** [comment]
thanks for the reply, so i did needed to change to zabbix server as the client  because i want to check the info on the zabbix server itself

so the data is coming in but i did see this so not sure if its relevant 
```

root@postgre:~# service mamonsu status
● mamonsu.service - LSB: Start mamonsu daemon
   Loaded: loaded (/etc/init.d/mamonsu; generated)
   Active: active (exited) since Sun 2020-08-09 19:37:34 -05; 1min 44s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 10850 ExecStop=/etc/init.d/mamonsu stop (code=exited, status=0/SUCCESS)
  Process: 10865 ExecStart=/etc/init.d/mamonsu start (code=exited, status=0/SUCCESS)

Aug 09 19:39:04 postgre mamonsu[10865]: [ERROR] 2020-08-09 19:39:04,769 - XLOG        -        catch error: (u'ERROR', u'ERROR', u'42501', u'permission denied for function pg_ls_dir', u'aclchk.c', u'3489', u'aclcheck_error', u'', u'')
Aug 09 19:39:04 postgre mamonsu[10865]: [INFO] 2020-08-09 19:39:04,769 - XLOG        -        hint: enable debug level to full exception trace
Aug 09 19:39:14 postgre mamonsu[10865]: [INFO] 2020-08-09 19:39:14,738 - PGSQL-(host=localhost db=zabbix user=zabbix port=5432)        -        connecting
Aug 09 19:39:14 postgre mamonsu[10865]: [INFO] 2020-08-09 19:39:14,738 - INSTANCE        -        started ...
Aug 09 19:39:14 postgre mamonsu[10865]: [INFO] 2020-08-09 19:39:14,740 - XLOG        -        started ...
Aug 09 19:39:14 postgre mamonsu[10865]: [INFO] 2020-08-09 19:39:14,747 - PGSQL-(host=localhost db=zabbix user=zabbix port=5432)        -        connected
Aug 09 19:39:14 postgre mamonsu[10865]: [ERROR] 2020-08-09 19:39:14,774 - INSTANCE        -        catch error: int() argument must be a string or a number, not 'NoneType'
Aug 09 19:39:14 postgre mamonsu[10865]: [INFO] 2020-08-09 19:39:14,774 - INSTANCE        -        hint: enable debug level to full exception trace
Aug 09 19:39:14 postgre mamonsu[10865]: [ERROR] 2020-08-09 19:39:14,780 - XLOG        -        catch error: (u'ERROR', u'ERROR', u'42501', u'permission denied for function pg_ls_dir', u'aclchk.c', u'3489', u'aclcheck_error', u'', u'')
Aug 09 19:39:14 postgre mamonsu[10865]: [INFO] 2020-08-09 19:39:14,781 - XLOG        -        hint: enable debug level to full exception trace
```
Also i see that you have an option about tuning? by running this command `mamonsu tune`
what does it do?

Thank you

**Comment by casperr0** [comment]
1 ) Have you done` mamonsu bootstap` ? 
It lets you get all the necessary metrics without superuser rights. Read details about bootstap in paragraph 1 here: 
https://postgrespro.com/docs/postgrespro/11/mamonsu#MAMONSU-INSTALLATION-AND-SETUP

errors such as "permission denied ..." for functions show that PostgreSQL user which you are using to connect to mamonsu doesn't have right to perform certain functions. So I would recommend you to perform ` mamonsu bootstap`  or give your current user superuser rights ( non recommended)

2) about error "INSTANCE        -        catch error: int() argument must be a string or a number, not 'NoneType'" -
You have installed mamonsu 2.4.5. from packages and it doesn't have the latest fix https://github.com/postgrespro/mamonsu/pull/142. So this error is not relevant. It will be fixed in the next release.

3) about `mamonsu tune`
  This command edits some settings in postgresql.conf according to your machine parameters. 
  Read more here in "Tuning Postgres Pro and System Configuration" section:
  https://postgrespro.com/docs/postgrespro/11/mamonsu

All documentation is also available in Russian and for PostgreSQL version starting from  9.6

**Comment by killmasta93** [comment]
Thanks for the reply, what i did is give the zabbix user the admin privileges as its the only user.  
do i need to restart the server or should it work after?

```
postgres=# \du;
                                   List of roles
 Role name |                         Attributes                         | Member of 
-----------+------------------------------------------------------------+-----------
 postgres  | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
 zabbix    | Superuser   
```

Thank you

**Comment by casperr0** [comment]
Restarting server is not required

**Comment by killmasta93** [comment]
thanks for the reply, the only error that im still seeing is this 
very odd because the user which is zabbix gave it permissions super user

![image](https://user-images.githubusercontent.com/13953629/90445704-b474ca80-e0a5-11ea-956f-198fd0aa9691.png)

**Comment by casperr0** [comment]
As I see on screenshots the problem appeared at "2020-08-09 19:47:41"  
So maybe you could try to update problems on zabbix server to be more  up-to-date

**Comment by killmasta93** [comment]
thanks for the reply, the issue is that the alert has not gone away i thought after giving the zabbix user the SA should of disappeared, i tried to reboot the server thinking that might be the issue but still no luck
Thank you

**Comment by casperr0** [comment]
In this case, I would suggest manually remove this particular trigger from Zabbix-Server. If the problem is gone (and it looks like it is gone ) the trigger would not be fired again.

**Comment by killmasta93** [comment]
thanks for the reply, so i removed the template and readded it but got this alert

![image](https://user-images.githubusercontent.com/13953629/90798910-2b91a500-e2d8-11ea-829e-8016ba57ea00.png)

**Comment by killmasta93** [comment]
thank you
