### ISSUE TITLE
[ERROR] 2020-08-21 14:34:41,690 - ZBX-192.168.0.31:10051        -       On request:

### ISSUE THREAD

**Issue by vanchezzz** [postgrespro/mamonsu#146]
Настроил все по мануалу, но при старте такая ошибка agent.log
`[ERROR] 2020-08-21 14:34:41,690 - ZBX-192.168.0.31:10051        -       On request:
{"data": [{"host": "192.168.0.31", "value": "0.0", "key": "pgsql.tuples[updated]", "clock": 1598009671}, {"host": "192.168.0.31", "value": "514.2", "key": "pgsql.tuples[returned]", "clock": 1598009671}, {"host": "192.168.0.31", "value": "15.6", "key": "pgsql.tuples[inserted]", "clock": 1598009671}, {"host": "192.168.0.31", "value": "108.3", "key": "pgsql.tuples[fetched]", "clock": 1598009671}, {"host": "192.168.0.31", "value": "0.0", "key": "pgsql.tuples[deleted]", "clock": 1598009671}, {"host": "192.168.0.31", "value": "0.0", "key": "pgsql.temp[files]", "clock": 1598009671}, {"host": "192.168.0.31", "value": "0.0", "key": "pgsql.temp[bytes]", "clock": 1598009671}, {"host": "192.168.0.31", "value": "1.0", "key": "pgsql.events[xact_rollback]", "clock": 1598009671}, {"host": "192.168.0.31", "value": "0.0", "key": "pgsql.events[deadlocks]", "clock": 1598009671}, {"host": "192.168.0.31", "value": "0.0", "key": "pgsql.events[conflicts]", "clock": 1598009671}, {"host": "192.168.0.31", "value": "0.3", "key": "pgsql.blocks[read]", "clock": 1598009671}, {"host": "192.168.0.31", "value": "279.9", "key": "pgsql.blocks[hit]", "clock": 1598009671}, {"host": "192.168.0.31", "value": "7.4", "key": "pgsql.transactions[total]", "clock": 1598009671}], "request": "sender data", "clock": 1598009681}
get response with failed items:
{"response":"success","info":"processed: 0; failed: 13; total: 13; seconds spent: 0.000476"}
[INFO] 2020-08-21 14:34:41,697 - INSTANCE       -       started ...
[ERROR] 2020-08-21 14:34:41,714 - INSTANCE      -       catch error: int() argument must be a string or a number, not 'NoneType'
[INFO] 2020-08-21 14:34:41,714 - INSTANCE       -       hint: enable debug level to full exception trace`

Порты открыты и доступны телнетом, zabbix agent нормально работает, таже ошибка если конфиге mamonsu вместо адреса указать localhost. В чем проблема подскажите пожалуйста?
Спасибо. 
Конфиг

` [postgres]
enabled = True
user = mamonsu
password = None
database = mamonsu
host = localhost
port = 5432
application_name = mamonsu
query_timeout = 10

[zabbix]
enabled = True
client = Zabbix_server
address = 192.168.0.31
port = 10051

[system]
enabled = True

[sender]
queue = 2048

[agent]
enabled = True
host = 127.0.0.1
port = 10052  `

**Comment by vanchezzz** [comment]
> Это разные шаблоны: шаблон Template DB PostgreSQL - это https://www.zabbix.com/integrations/postgresql#tab:official1
> он для Zabbix Agent. А mamonsu - это zabbix trapper, для него нужен другой шаблон, который нужно выгрузить командой export template и потом загрузить на Zabbix Server. Подробнее тут :
> https://postgrespro.ru/docs/postgrespro/11/mamonsu в разделе "Установка и подготовка" , пункт 3
> 
> mamonsu не будет работать с шаблоном Template DB PostgreSQL.
> 
> или Вы установили и Zabbix Agent и mamonsu на одном хосте для работы с одной базой и они одноврменно собирают данные и отдают на один Zabbix Server? В этом случае всё должно работать, просто нужно создать два хоста на Zabbix Server, с шаблонами для zabbix agent и mamonsu соответственно и правильно распределить порты

Да, оба агента отправляли на 10050, в этом и была проблема.

**Comment by casperr0** [comment]
Отлично, что разобрались!

**Comment by vanchezzz** [comment]
Большое спасибо!
