### ISSUE TITLE
Zabbix agent 5.2.3 working as non agent2

### ISSUE THREAD

**Issue by itkroplis** [postgrespro/mamonsu#150]
Эсли използуется zabbix agent 5.2.3 должен ли работат mamonsu в режиме не zabbix агент2? 

Эсли използуется zabbix agent 5.2.3 как zabbix.agent2 что надо вписиват в zabbix.agent.config?

Эсли използую Zabbix Server 5.2.3 + Postgresql12 + TimeScaleDB (PostgreSQL) 12.5 (Ubuntu 12.5-1.pgdg20.04+1). Доступен где то мануал по настроике? 

Без вариантов получаю подобние ошибки. DB user role superuser 

[ERROR] 2021-01-05 20:27:06,842 - ZBX-127.0.0.1:10051   -       On request:
{"request": "sender data", "data": [{"host": "zabbix", "key": "pgsql.connections[max_connections]", "value": "100", "clock": 1609878416}, {"host": "zabbix"
get response with failed items:
b'{"response":"success","info":"processed: 0; failed: 36; total: 36; seconds spent: 0.000270"}'

**Comment by casperr0** [comment]
Mamonsu - отдельная утилита и его работа не связана с работой Zabbix Agent 2, поэтому mamonsu не может работать в режиме Zabbix Agent 2 или наоборот. mamonsu работает в своем режиме.

Если Вы имеете ввиду как заполнять zabbix_agent2.conf, то инструкция есть на https://www.zabbix.com/documentation/current/ru/manual/concepts/agent2. 

Мануал для настройке при таких конкретных параметрах не доступен. Однако, Вы можете найти универсальный мануал для настройки mamonsu тут https://postgrespro.ru/docs/postgrespro/12/mamonsu

Судя по ошибке, возможно, проблемы с настройкой портов на заббикс сервера. Проверьте корректность данных в секции [zabbix] в файле agent.conf и убедитесь , что указали верный address и port для заббикс сервера. на самом заббикс сервере убедитесь, что  к соответствующему Host привязан шаблон Mamonsu
