### ISSUE TITLE
Archiving metrics are not collected if archive_mode is set to "always"

### ISSUE THREAD

**Issue by kuzmindb** [postgrespro/mamonsu#151]
Hey!

Is there any reason why archiving metrics are not collected if **archive_mode** is set to "always"?
https://github.com/postgrespro/mamonsu/blob/2.6.2/mamonsu/plugins/pgsql/plugin.py#L50-L56

> **archive_mode (enum)**
In addition to off, to disable, there are two modes: on, and always. During normal operation, there is no difference between the two modes, but when set to always the WAL archiver is enabled also during archive recovery or standby mode. In always mode, all files restored from the archive or streamed with streaming replication will be archived (again).

https://postgrespro.com/docs/postgresql/11/runtime-config-wal#RUNTIME-CONFIG-WAL-ARCHIVING

**Comment by casperr0** [comment]
Thank you for the issue
We will fix this in the next version

**Comment by casperr0** [comment]
This is fixed in the latest release 2.7.0
