### ISSUE TITLE
Zabbix получает ошибки от mamonsu "Last: . Total count: 1."

### ISSUE THREAD

**Issue by v3n1kk** [postgrespro/mamonsu#154]
Периодически стал срабатывать триггер Mamonsu plugin errors on %HOSTNAME%. Last: . Total count: 1.
Логи mamonsu при этом ошибок не содержат. Информацию что именно это за ошибка получить не удается.
Данная проблема стала проявляться сразу на нескольких хостах, где используется mamonsu. 
Версия mamonsu 2.4.5
В каком направлении искать причину ошибки?

**Comment by popov83** [comment]
Попробуйте поискать в логе текст "catch error: ". После этой фразы должна быть ошибка.
Включите log level= debug в конфиге.
Уточните версию, команда  mamonsu --version

**Comment by v3n1kk** [comment]
В логе записи с "catch error: " отсутствуют.
Включил debug на одной из нод, попробуем отловить ошибку. По результату отпишусь через пару-тройку дней. 
Версия mamonsu 2.4.5 на подавляющем большинстве серверов. Но такая же проблема наблюдается и на сервере с mamonsu 2.6.2. 
Дебаг включил на сервере с версией 2.6.2

**Comment by v3n1kk** [comment]
Подобная проблема наблюдалась из-за использования traefik для балансировки нагрузки на zabbix (application). 
Сменили решение на haproxy и проблема ушла.
