### ISSUE TITLE
Предложение: добавить мониторинг наличия неактивных слотов репликации

### ISSUE THREAD

**Issue by xinferum** [postgrespro/mamonsu#155]
Добрый день.

Хочу предложить добавить на мониторинг проверку наличия неактивных слотов репликации на сервере PostgreSQL, например таким образом:
`select count(*) from pg_replication_slots where active = false;`

И триггер на их наличие.
Сталкивался с ситуацией, когда на одном мастере не удалили вовремя слот и это привело к накоплению WAL. В mamonsu подобную метрику не нашел.

**Comment by sanstepan** [comment]
Плюсую!

**Comment by sgrinko** [comment]
Согласен,
такой алёрт очень нужен.
В идеале наверное здесь будет лучше использовать discovery чтобы алёрт приходил осмысленный и содержал в себе имя слота

**Comment by casperr0** [comment]
добавили в версии 2.7.0
