### ISSUE TITLE
Zabbix-server 4.4.5 и mamonsu 2.6.2

### ISSUE THREAD

**Issue by mixmind** [postgrespro/mamonsu#156]
Всем привет. 

Почти все items в zabbix server которые связаны с ОС и их тип zabbix-agent не работают , судя по keys которые использует mamonsu они не совпадают с zabbix keys. 

Пример:
```
vfs.fs.size[/,free] в стандартном template zabbix
system.vfs.free[/] в template от mamonsu
```
Вот что в логе mamonsu eсли пытаюсь дернуть item вручную таким запросом
zabbix_get -s IP -k system.memory.active
`2021-04-06 16:04:48,282 - AGENTAPI	-	code 400, message Bad request syntax ('ZBXD\x01\x14\x00\x00\x00\x00\x00\x00\x00system.memory.active')
`
Есть ли поддержка этой версии zabbix-server или есть другие пути обойти это?

**Comment by casperr0** [comment]
Привет!

Ключи для мамонсу относятся к типу zabbix-trapper, поэтому не должны совпадать с ключами типа zabbix-agent

Уточните пожалуйста какой шаблон вы используете.

Учтите, что mamonsu не работает со стандартным шаблоном от zabbix.
 Получить шаблон для mamonsu можно через комнаду:
`mamonsu export template имя_файла.xml`

Подробнее можно почитать об этом в документации в разделе "Установка и настройка"
https://postgrespro.ru/docs/postgrespro/11/mamonsu

**Comment by casperr0** [comment]
Можете привести пример items , которые имеют тип zabbix -agent ?

К сожалению, нельзя понять по логу какие именно items failed. 
Можно сделать так: посмотреть в zabbix server во вкладке latest data в веб интерфейсе в каком item данные не появились  (он будет отмечен красным)

**Comment by mixmind** [comment]
Да, конечно
На сколько я вижу есть почти столько одинаковое количество items  zabbix -agent и  zabbix -trapper
![Screenshot from 2021-04-07 11-57-14](https://user-images.githubusercontent.com/33128809/113839867-c3290280-9798-11eb-8471-0a85f39bb45e.png)
![Screenshot from 2021-04-07 11-56-47](https://user-images.githubusercontent.com/33128809/113839885-c7552000-9798-11eb-998d-77aee3b5660f.png)

По последним данным на zabbix-server не видно кто не отработал, единственное еще что может быть что discovery может падает. Я выключил сейчас os metrics, и у меня mamonsu только для pg_probackup работает, а для os metrics, я включил рядом zabbix-agent..

**Comment by casperr0** [comment]
Судя по скриншоту у вас каким-то образом слились на хосте items из двух шаблонов (zabbix trapper & zabbix agent) и поэтому некоторые items дублируются , напр. system.disk.all_write_b. Хотя с другой стороны они отмечены как disabled. Это вы их отключили?

Может попробовать сделать заново: 
1. выгрузить шаблон (обратите внимание на опции  [--template-name=имя_шаблона]
    [--application=имя_приложения] - они позволяют менять имя шаблона и приложения, которое отображается на заббикс сервер , т.е. сейчас у вас имя шаблона PostgresPro-Linux ) 
 2. загрузить новый шаблон на заббикс сервер
 3. очистить хост от старых шаблонов
 4. прикрепить к хосту новый шаблон
 
 Обратите внимание, что items в шаблоне  должно быть чуть больше 130, но не более 250, как это сейчас у вас

**Comment by mixmind** [comment]
Да, я сам выключил, так как все равно не работали. 

Окей, попробуй поменять шаблон. Отпишусь поможет ли
Спасибо

**Comment by mixmind** [comment]
Заменил template, теперь только от zabbix-trapper остались items,вроде работает нормально.

Спасибо,
 можно закрывать issue

**Comment by casperr0** [comment]
Отлично!
