### ISSUE TITLE
Ошибка в адресе репозитория

### ISSUE THREAD

**Issue by xinferum** [postgrespro/mamonsu#158]
Добрый день.

После выхода релиза mamonsu 2.7.1 начал обновлять пакет на серверах и наткнулся в Ubuntu 18.04 на проблему с репозиторием:

> W: Не удалось получить http://localrepo.l.postgrespro.ru/stable/mamonsu/ubuntu/dists/bionic/InRelease  Не удалось разрешить «localrepo.l.postgrespro.ru»

Мы обычно переустанавливаем mamonsu с нуля, при помощи ansible, соответственно и файл apt-repo-add.sh для установки репозитория выполняем каждый раз. В самом файле http://repo.postgrespro.ru/mamonsu/keys/apt-repo-add.sh обнаружил что указан локальный адрес в качестве репозитория:
```
#!/bin/sh
REPO=http://localrepo.l.postgrespro.ru/stable/mamonsu
PRODUCT_NAME="Mamonsu"
...
```

Тоже самое обнаружилось и в CentOS 7 при установке на чистую систему:

> failure: repodata/repomd.xml from mamonsu: [Errno 256] No more mirrors to try.
> http://localrepo.l.postgrespro.ru/stable/mamonsu/centos/7/os/x86_64/rpms/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: localrepo.l.postgrespro.ru; Unknown error

В rpm-файле репозитория http://repo.postgrespro.ru/mamonsu/keys/centos.rpm тоже указан локальный адрес репозитория:
```
[mamonsu]
name=Mamonsu Packages for centos - $basearch
baseurl=http://localrepo.l.postgrespro.ru/stable/mamonsu/centos/$releasever/os/$basearch/rpms
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-POSTGRESQL-PRO
```

В то же время на машине с CentOS 7 где уже давно установлен репозиторий mamonsu, адрес выглядит вот так:
```
...
baseurl=http://repo.postgrespro.ru/mamonsu/centos/$releasever/os/$basearch/rpms
...
```

Вероятно была допущена ошибка в адресе репозитория.

**Comment by popov83** [comment]
Попоробуйте сейчас. Ошибка должна быть исправлена.

**Comment by xinferum** [comment]
Здравствуйте.

Развернул сейчас на чистых ВМ с Ubuntu 18.04 и CentOS 7 Postgres и установил mamonsu. Репозитории корректные:
Ubuntu:
```
# Repositiory for 'Mamonsu'
deb https://repo.postgrespro.ru/mamonsu/ubuntu bionic main
```

CentOS:
```
[mamonsu]
name=Mamonsu Packages for centos - $basearch
baseurl=https://repo.postgrespro.ru/mamonsu/centos/$releasever/os/$basearch/rpms
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-POSTGRESQL-PRO
```

Спасибо!

**Comment by sergeyshaklein** [comment]
Здравствуйте 
curl -o apt-repo-add.sh https://repo.postgrespro.ru/pg1c-14/keys/apt-repo-add.sh

Видимо опять ошибка в скрипте (локальный репозиторий)
REPO=http://localrepo.l.postgrespro.ru/stable/archive/pg1c-14.1

**Comment by cuprumtan** [comment]
@sergeyshaklein попробуйте этот скрипт:
```bash
wget http://repo.postgrespro.ru/pg1c-14/keys/pgpro-repo-add.sh
```
