### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by kfra71** [postgrespro/mamonsu#169]
Hi, I am getting this error while importing the .xml template to Zabbix 5.0:

Invalid tag "/zabbix_export/templates/template(1)/discovery_rules/discovery_rule(4)": unexpected tag "filter27".

Can you kindly address me to the right point?

Francesco.

**Comment by kfra71** [comment]
I am using Windows Server 2019 as operating system,

**Comment by cuprumtan** [comment]
Hi!
After code inspecting, I found a bug in Windows template generation module. This will be fixed in next patch.
Here fixed latest Mamonsu versions templates for Zabbix:
[Mamonsu 3.0.0 Windows](https://pastebin.com/9FaeUmC5)
[Mamonsu 3.1.0 Windows](https://pastebin.com/mKAYS8Cq)

**Comment by cuprumtan** [comment]
Fixed in a4ffe96095608658ade9dee83556c75c1b86793f
