### ISSUE TITLE
документирование agent.conf

### ISSUE THREAD

**Issue by sgrinko** [postgrespro/mamonsu#17]
в описании к файлу конфигурации:
- надо обратить особое внимание на регистр букв, так как в таких опциях как - file,password,... очень важно писать "None", но не "none". Так как только при указании с большой буквы это понимается как отсутствие
- имя клиента "client" здесь нужно указывать имя "Host Name" как указано в zabbix (Configuration->HOSTS). Мы же изначально указали туда "DNS name" и долго не могли понять в чём проблема.
- возникли вопросы по параметрам файла конфигуации - [log],[sender], [health], [bgwriter], ... нужно документировать. Мы например, чтобы немного понять, что происходит в [log] написали - 
  [log]
  file = file.log
  level = DEBUG
  format = [%(levelname)s] %(asctime)s - %(name)s - %(message)s

**Comment by bot659** [comment]
Хотелось бы чтобы параметр Interval, прописаннный в файле mamonsu/plugins/pgsql/databases.py, находился в конфиге agent.conf.

**Comment by vadv** [comment]
на самом деле изменение interval завязано на https://github.com/postgrespro/mamonsu/blob/master/mamonsu/lib/template.py#L42
тоесть если указываешь свой интервал в конфиге, то при генерации темплейта нужно указывать обязательно конфиг, который переопределяет его

**Comment by dan-aksenov** [comment]
Такой вопрос 
```
[zabbix]
; zabbix server address
address = 2 адреса через запятую.
```
Дает вот такое
```
[ERROR] 2016-12-16 14:46:25,700 - ZBX-2 моих адреса:10051 -       catch error: [Errno -2] Name or service not known
```
Есть возможность указать несколько адресов?

**Comment by vadv** [comment]
> Есть ли возможность указать несколько адресов заббикс серверов?
нет, пока такой возможности нет
она появиться когда @gsmol реализует несколько postgresql - серверов, так ведь Гриш?

**Comment by dan-aksenov** [comment]
В конфиге указал
``[postgres]``
``enabled = False``
Но информация по базе продолжает поступать.
Что я делаю не так?

**Comment by vadv** [comment]
а точно плагин отнаследован от этого Plugin? 
`from mamonsu.plugins.pgsql.plugin import PgsqlPlugin as Plugin`

**Comment by dan-aksenov** [comment]
А порт на котором слушает заббикс сервер указать можно?

**Comment by vadv** [comment]
```
        config.add_section('zabbix')
        config.set('zabbix', 'enabled', str(True))
        config.set('zabbix', 'client', socket.gethostname())
        config.set('zabbix', 'address', '127.0.0.1')
        config.set('zabbix', 'port', str(10051))
```

```
[zabbix]
address = x.x.x.x
port = yyy
```

**Comment by dan-aksenov** [comment]
а посылать на заббикс прокси возможно?
а то пока не идут данные (

**Comment by vsbace** [comment]
Это описание - "имя клиента "client" здесь нужно указывать имя "Host Name" как указано в zabbix (Configuration->HOSTS)." нужно обязательно в документе описать, я пол дня потерял, пока эту тему не нашел. Спасибо огромное! )

**Comment by OSidorenkov** [comment]
Запускаю несколько инстансов приложения mamonsu для мониторинга нескольких инстансов БД. Получаю ошибку
```[INFO] 2018-05-03 13:09:20,137 - AGENTAPI	-	Starting at http://127.0.0.1:10052
[INFO] 2018-05-03 13:09:20,138 - AGENTAPI	-	started ...
[ERROR] 2018-05-03 13:09:20,138 - AGENTAPI	-	catch error: [Errno 98] Address already in use

**Comment by nikolaev-rd** [comment]
Вот [тут](https://github.com/postgrespro/mamonsu/issues/78#issuecomment-263860078) полный вариант конфига есть.
Вам нужно добавить что-то такое в ваш конфиг (соответственно разный порт для каждого инстанса mamonsu):
```
[agent]
port = 10053
```

**Comment by popov83** [comment]
В новой версии конфигурационный файл со всеми возможными параметрами
