### ISSUE TITLE
Некорректный репозиторий для Centos 8

### ISSUE THREAD

**Issue by ktulkhu** [postgrespro/mamonsu#170]
Устанавливаю репозиторий: 
rpm -i https://repo.postgrespro.ru/mamonsu/keys/centos.rpm

в репозитории прописан некорректный baseurl:
cat mamonsu.repo
  [mamonsu]
  name=Mamonsu Packages for centos - $basearch
  baseurl=http://localrepo.l.postgrespro.ru/stable/mamonsu/centos/$releasever/os/$basearch/rpms
  enabled=1
  gpgcheck=1
  gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-POSTGRESQL-PRO

Уже встречал в issues подобрый запрос и он уже закрыт.  Но проблема возобновилась.

**Comment by cuprumtan** [comment]
Обновили содержимое репозитория, теперь baseurl указан корректно.
