### ISSUE TITLE
Не импортируется шаблон mamonsu 3.0.0 в Zabbix 5.0

### ISSUE THREAD

**Issue by Klink0v** [postgrespro/mamonsu#173]
Сгенерированный при помощи mamonsu 3.0.0 шаблон не импортируется в Zabbix 5.0 с мотивацией
`Incorrect value "" for int field "max_columns".`

Есть два возможных workaround-а:

1. Удалить из XML-файла секцию "screens".
2. Импортировать шаблон в Zabbix 4, экспортировать его оттуда в XML, затем импортировать в Zabbix 5.

Прошу по возможности исправить.

**Comment by cuprumtan** [comment]
Closed due linked issue #177
