### ISSUE TITLE
Streamin lag ложные срабатывания

### ISSUE THREAD

**Issue by sanstepan** [postgrespro/mamonsu#174]
На  реплике "спокойной" базы с низкой активностью нередки ложные срабатывания:
Problem name: PostgreSQL streaming lag too high on .... 
В числовом значении он и впрямь кажется высоким, но это, похоже, просто проблема методики подсчета этой метрики.

**Comment by sgrinko** [comment]
укажите на какой версии у вас эта проблема.

**Comment by sanstepan** [comment]
mamonsu --version
mamonsu 3.0.0

Утверждается, что в 3.1 исправлено

**Comment by sgrinko** [comment]
В latest версии такой проблемы быть уже не должно. В версии 3.0 подтверждаю, что так и было. Заводил такой баг #166 
По возможности обновитесь.
