### ISSUE TITLE
Добавить в лог mamonsu вывод версии при старте

### ISSUE THREAD

**Issue by xinferum** [postgrespro/mamonsu#175]
Добрый день.

Есть предложение по небольшой косметической доработке - добавить в лог mamonsu вывод запустившейся версии при старте.
В некоторых ситуациях это было бы полезно. Иногда приходится тестировать mamonsu устанавливая его вручную, не через пакеты (например, самые свежие, которых в виде пакетов еще нет), и понять какая версия сейчас запущена на сервере довольно сложно.

Сейчас такой информации в логе нет:
```
[INFO] 2021-11-17 14:50:31,029 - root   -   Start mamonsu
[INFO] 2021-11-17 14:50:31,040 - HEALTH -   started ...
```

**Comment by cuprumtan** [comment]
Добавлено в версию 3.2.0
