### ISSUE TITLE
Ошибка при импорте шаблона в zabbix

### ISSUE THREAD

**Issue by pkarezin** [postgrespro/mamonsu#177]
Добрый день. Установлен пакет mamonsu-3.0.0. Выполнен экспорт шаблона `mamonsu export template`. При попытке импорта шаблона в zabbix 4.4 (через web-интерфейс) получаю ошибку: 
```
Import failed
Incorrect value "" for int field "max_columns".
```

**Comment by pkarezin** [comment]
В качестве временного решения, можно удалить из файла шаблона секцию `<screens>` , тогда импорт шаблона проходит без ошибок.

**Comment by cuprumtan** [comment]
Linked issue: #173
Постарались исправить поведение в версии 3.2.0
