### ISSUE TITLE
Обновление сборки в репозитории.

### ISSUE THREAD

**Issue by pkarezin** [postgrespro/mamonsu#178]
Просьба обновить сборку в репозитории https://repo.postgrespro.ru/ так как на текущий момент, из репозитория возможно установить только mamonsu версии 3.0.0.

**Comment by sgrinko** [comment]
при сборке пакета для новых версий прошу следить за корректность ссылок внутри инсталяционных пакетов!

$ yum list available | grep mamonsu
http://localrepo.l.postgrespro.ru/stable/mamonsu/centos/7/os/x86_64/rpms/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: localrepo.l.postgrespro.ru; Неизвестная ошибка"

`localrepo.l.postgrespro.ru` - как-то попал ваш локальный путь.

об этом также писалось ещё в #170

**Comment by cuprumtan** [comment]
Добавили в репозиторий версию 3.1.2
