### ISSUE TITLE
Лаг репликации на primary сервере

### ISSUE THREAD

**Issue by pkarezin** [postgrespro/mamonsu#180]
Добрый день, столкнулись со следующей проблемой при использовании mamonsu 3.1.2 и PostgreSQL 9.6.

Если процесс postmaster будет завершен некорректно (kill -9), то после запуска сервера будет взведен триггер `PostgreSQL: streaming replication lag`, даже если это primary или standalone сервер.
`SELECT now() - pg_last_xact_replay_timestamp()` будет отображать время с момента запуска startup на сервере.

```
# SELECT now() - pg_last_xact_replay_timestamp();
    ?column?
----------------
 00:21:15.10736
(1 row)
```

**Comment by sgrinko** [comment]
Подтверждаю.
В режиме bootstrap в функции `mamonsu.timestamp_get()` не учтен вариант запуска данной функции на master реплике.
Дело в том, что при вычислении выражения мы получаем LSN = NULL  - это даёт ложь и вычисляется `ELSE` 
![изображение](https://user-images.githubusercontent.com/10084993/148724882-9b87cfe2-90df-487b-bad5-daf6f35f1c07.png)

Необходимо изменить функцию `mamonsu/mamonsu/plugins/pgsql/driver/pool.py` таким образом:

```
"replication_lag_slave_query": (
	"""
	SELECT CASE WHEN coalesce(pg_last_{1}(), '0/00000000') = coalesce(pg_last_{2}(), '0/00000000')
				THEN 0
				ELSE extract (epoch FROM now() - coalesce(pg_last_xact_replay_timestamp(), now() - INTERVAL '{0} seconds'))
		   END;
	""",
	"""
	SELECT mamonsu.timestamp_get();
	"""
),
```
->
```
"replication_lag_slave_query": (
	"""
	SELECT CASE WHEN not pg_is_in_recovery() or coalesce(pg_last_{1}(), '0/00000000') = coalesce(pg_last_{2}(), '0/00000000')
				THEN 0
				ELSE extract (epoch FROM now() - coalesce(pg_last_xact_replay_timestamp(), now() - INTERVAL '{0} seconds'))
		   END;
	""",
	"""
	SELECT mamonsu.timestamp_get();
	"""
),
```

**Comment by cuprumtan** [comment]
Добрый день! Добавили фикс в версию [3.3.0](https://github.com/postgrespro/mamonsu/releases/tag/3.3.0).

**Comment by sgrinko** [comment]
Спасибо!
Будем пробовать
