### ISSUE TITLE
Метрика для статуса ноды: master/standby

### ISSUE THREAD

**Issue by DRVTiny** [postgrespro/mamonsu#181]
Здравствуйте!

Был очень удивлён тому, что нет такой метрики, хотя внутри кода плагинов постоянно делаются запросы с CASE WHEN pg_in_recovery()
У нас ДБА как раз очень хотят знать, что нода переключила состояние: была slave, стала master, например.
Как это реализовать с mamonsu?

Спасибо!

**Comment by cuprumtan** [comment]
Добрый день! Да, само состояние во многих запросах используется, но явно нигде не отображается.
Метрика и соответствующий триггер, реагирующий на смену состояния ноды, будут добавлены в следующий патч.
