### ISSUE TITLE
Error on dashboard upload

### ISSUE THREAD

**Issue by roruizi2022** [postgrespro/mamonsu#186]
Версия Zabbix 6.2.0. На хосте mamonsu 3.5.0. Пробовал с версией 3.4, та же ошибка. 
Группа шаблонов [Templates] есть и в нее ранее загружен стандартный шаблон Mamonsu PostgreSQL Linux.
Пробовал создавать новый шаблон с другим именем. Ошибка та же.
```
mamonsu zabbix dashboard upload 'Mamonsu PostgreSQL Linux'
Dashboard upload error: Error response from zabbix api: {
  "code": -32500,
  "message": "Application error.",
  "data": "Group \"Templates\" does not exist."
```
Спасибо!

**Comment by cuprumtan** [comment]
Добрый день! Добавили фикс в версию [3.5.2](https://github.com/postgrespro/mamonsu/releases/tag/3.5.2).

**Comment by roruizi2022** [comment]
> Добрый день! Добавили фикс в версию [3.5.2](https://github.com/postgrespro/mamonsu/releases/tag/3.5.2).

Спасибо! Работает.
