### ISSUE TITLE
новая метрика - Network

### ISSUE THREAD

**Issue by sgrinko** [postgrespro/mamonsu#20]
будет хорошо иметь настроенный набор метрик для мониторинга загрузки сетевой карты

**Comment by sgrinko** [comment]
Предлагаю реализовать мониториг вот этих двух счётчиков:
Два главных счетчика — общей скорости в байт/с Bytes Total/sec и длины очереди вывода Output Queue Length. Счетчик Bytes Total/sec следует сопоставлять с принятым базовым уровнем. Если сетевой обмен значительно возрастает по сравнению с базовым уровнем, обычно это означает, что нагрузка на сервер существенно возросла по сравнению с нагрузкой, которая наблюдалась при определении базового уровня. Но это может также служить индикатором сетевой атаки или показывать необходимость разгрузки некоторых процессов. Счетчик Output Queue Length поможет определить, что требуется предпринять. Если среднее значение счетчика более двух, это значит, что сетевой интерфейс (или пропускная способность сетевой инфраструктуры) не справляется с передачей данных, предоставляемых сервером. Другими словами, сервер выдает данные с большей скоростью, чем сетевой интерфейс в состоянии передать.

**Comment by vadv** [comment]
```python
from mamonsu.lib.plugin import Plugin
from .helpers import PerfData


class Network(Plugin):

    Items = [
        # perf_item, zbx_key, desc, delta, unit, (color, site)
        (r'\Network Interface(*)\Output Queue Length', '[total_output_queue]',
            'Output Queue Length', None, ('0000CC', 0)),

        (r'\Network Interface(*)\Bytes Total/sec', '[total_bytes]',
            'Bytes Total', 'b', ('00CC00', 1))
    ]

    def run(self, zbx):
        perf_services = []
        for item in self.Items:
            perf_services.insert(0, item[0])
        data = PerfData.get(perf_services, delay=1000)
        for idx, item in enumerate(self.Items):
            zbx.send('system.network{0}'.format(item[1]), data[idx])

    def items(self, template):
        result = ''
        for item in self.Items:
            result += template.item({
                'name': '{0}'.format(item[2]),
                'key': 'system.network{0}'.format(item[1]),
                'units': item[3]
            })
        return result

    def graphs(self, template):
        items = []
        for item in self.Items:
            if item[4] is not None:
                items.append({
                    'key': 'system.network{0}'.format(item[1]),
                    'color': item[4][0],
                    'yaxisside': item[4][1]
                })
        graph = {
            'name': 'Network overview', 'items': items, 'type': 1}
        return template.graph(graph)
```

**Comment by vadv** [comment]
https://github.com/postgrespro/mamonsu/tree/master/win/0.1.1
