### ISSUE TITLE
добавить метрики для WAL файлов, buffer cache

### ISSUE THREAD

**Issue by sgrinko** [postgrespro/mamonsu#21]
пример можно посмотреть здесь
https://github.com/lesovsky/zabbix-extensions/tree/master/files/postgresql
причём надо иметь ввиду, что запрос данных по buffer cache - это очень тяжёлый запрос и его спрашивать часто не следует, будет хорошо, если будет отдельная настройка по частоте с которой агент делает запрос в БД.

**Comment by vadv** [comment]
запроса по buffer_cache не будет, до той поры, пока он не перестанет блокировать весь shared_buffers на чтение.

**Comment by vadv** [comment]
с wal тоже проблемы:
```
postgres=> select count(*) from pg_ls_dir('pg_xlog');
ERROR:  must be superuser to get directory listings
```

**Comment by vadv** [comment]
короче ждем этого issue: https://github.com/postgrespro/mamonsu/issues/31

**Comment by vadv** [comment]
с версии 1.9.4 считаем кол-во xlog-файлов
