### ISSUE TITLE
Реализовать передачу в connection string имени приложения

### ISSUE THREAD

**Issue by sgrinko** [postgrespro/mamonsu#26]
Сейчас при подключении нет указания, что за приложение выполняет запрос:
,app=[[unknown]],
Пожалуйста, добавьте некое имя, чтобы можно было легко в log файле постгреса понимать, что эти запросы относятся к Zabbix агенту mamonsu

**Comment by vadv** [comment]
связано с этим:
https://github.com/mfenniak/pg8000/issues/41

**Comment by vadv** [comment]
https://github.com/mfenniak/pg8000/pull/106 отпулрекестил

**Comment by vadv** [comment]
Можно указать через конфиг `application_name` в разделе `postgres`, по дефолту - mamonsu
