### ISSUE TITLE
Ошибка при импортировании шаблона

### ISSUE THREAD

**Issue by laskin82** [postgrespro/mamonsu#29]
Zabbix Appliance 3.0 lts

Ошибка при импортировании шаблона

Детали

    Не верный XML тэг "/zabbix_export/templates/template(1)/items/item(1)": тэг "multiplier" пропущен.

[template.zip](https://github.com/postgrespro/mamonsu/files/195646/template.zip)

**Comment by vadv** [comment]
Прошу прислать валидный темплейт из zabbix appliance 3.0 lts выгруженый посредством этой же версии заббикс!

**Comment by laskin82** [comment]
[template_postgresql_server.zip](https://github.com/postgrespro/mamonsu/files/195653/template_postgresql_server.zip)

**Comment by laskin82** [comment]
экспортированный шаблон
[zbx_export_templates.zip](https://github.com/postgrespro/mamonsu/files/195656/zbx_export_templates.zip)

**Comment by vadv** [comment]
Видимо прийдеться писать отдельный экспорт для zabbix-2/zabbix-3.
zabbix3 игнорирует версию темплейта 2.
