### ISSUE TITLE
Import template.xml in zabbix 3.0

### ISSUE THREAD

**Issue by demony99** [postgrespro/mamonsu#30]
Hello!
Ошибка при импортировании
Детали
XML файл содержит фатальную ошибку 41:Specification mandate value for attribute data-pjax-transient [ Line: 51 | Column: 36 ]

**Comment by vadv** [comment]
привет!
уже рапортовали о проблемах с zabbix 3.0: https://github.com/postgrespro/mamonsu/issues/29 ждите обновления после 4-5 апреля.
