### ISSUE TITLE
Реализовать набор функций, которым требуются права superusers.

### ISSUE THREAD

**Issue by vadv** [postgrespro/mamonsu#31]
Иногда для мониторинга требуются функции, которым необходимо права superuser,
а пользователю mamonsu не хочется давать таких прав, поэтому необходимо реализовать поддержку файл с такими функциями и fallback при их отсутвии

**Comment by sgrinko** [comment]
Предлагаю обойти это через написание pgplsql функци созданных с правами superuser (SECURITY DEFINER). В этом случае непосредственно у пользователя mamonsu таких прав не будет. Для меня лично создание некоей обёртки в виде функций для работы мониторинга нет.

**Comment by vadv** [comment]
Мониторинг с админскими права - плохо,  `SECURITY DEFINER` уже лучше, но усложняется настройка. Необходимо решение как проще организовать первоначальную настройку.
Взять и распространять sql без которого не будет работать - выглядит просто и логично, но данные функции возможно понадобиться на всех базах, а не той изначальной, к которой коннектиться агент.

**Comment by sgrinko** [comment]
можно ведь это сделать например так:
c:\mamonsu\mamonsu.exe --install_superuser_function -U postgres -P <пароль> -H localhost -P 5432
и да конечно потребуется часть из них во все БД ставить.

**Comment by vadv** [comment]
реализовано с 1.9.3
