### ISSUE TITLE
Windows сервис и ведение лога.

### ISSUE THREAD

**Issue by sgrinko** [postgrespro/mamonsu#32]
В файле конфигурации agent.conf есть такие строки
[log]
file = mamonsu.log
level = INFO
format = [%(levelname)s] %(asctime)s - %(name)s	-	%(message)s

однако, при работе mamonsu как windows сервис нигде не удалось обнаружить наличие такого файла лога - "mamonsu.log". Наиболее ожидаемым местом появления этого файла считаю папку нахождения файла mamonsu.exe (если конечно нет точного пути в файле конфигурации).
При этом конечно ведение такого файла никак не должно отменять запись сообщений в windows application log.

**Comment by vadv** [comment]
думаю не захломлять windows application log и писать туда только сообщения о старте/стопе.
а текстовые логи вести в полном режиме отдельно.

**Comment by sgrinko** [comment]
Согласен.
