### ISSUE TITLE
Время опроса items внутри плагина не соотвествует времени опроса в zabbix

### ISSUE THREAD

**Issue by sgrinko** [postgrespro/mamonsu#34]
Сейчас например для плагина databases в агенте стоит время опроса 300 сек.
class Databases(Plugin):
    Interval = 300
Однако, для генерируемого шаблона items ставится время 60 сек.
Это приводит к тому, что zabbix думает, что в течении 5 минут он получает не одно, а 4 значения, 3-и из которых равны НОЛЬ.
![age_point](https://cloud.githubusercontent.com/assets/10084993/14433212/10a5f1b4-0016-11e6-9973-2a09e5e9b1fa.png)

Нужно, либо поправить в генерируемом шаблоне для zabbix время опроса с 60 сек. на 300 сек. либо внутри самого агента во время тишины плагина, повторять последнее известное значение.
Так как сейчас есть такая рассинхронизация, то нарушается вид графика и вместо линии мы видим точки.

**Comment by vadv** [comment]
сделаешь пул реквест?
нужно указать delay 300 ( https://github.com/postgrespro/mamonsu/blob/master/mamonsu/lib/template.py#L39 ) 
вот в этом месте: https://github.com/postgrespro/mamonsu/blob/master/mamonsu/plugins/pgsql/databases.py#L52

**Comment by sgrinko** [comment]
стал пробовать делать пул реквест....
попробовал сгенерить новый шаблон и получил "пустой" template.xml
[template.xml.zip](https://github.com/postgrespro/mamonsu/files/214412/template.xml.zip)
вкралась какая-то ошибка в код?
PS. Я пробовал генерить template на исходной копии без моих изменений.

**Comment by vadv** [comment]
ага, вижу багу. она плавающая. сейчас я думаю окончательно ее побежу

**Comment by sgrinko** [comment]
О!
Я вижу, что ты уже сам внёс все изменения :)
Спасибо.
