### ISSUE TITLE
У своих плагинов не формируется своя часть templatexml

### ISSUE THREAD

**Issue by sgrinko** [postgrespro/mamonsu#35]
Версия для WINDOWS
1) помещаю плагины в папку C:\mamonsu\ExtPlugins
2) создаю там пустой файл `__init__.py`

3) в файле agent.conf указываю: 
[plugins]
directory = C:\mamonsu\ExtPlugins
4) перезапуск службы
в качестве плагина использовал пример ExamplePlugin.py
5) генерирую template.xml командой
mamonsu -e template.xml

В полученном файле нет items и graph
Приложен log файл.
[mamonsu.zip](https://github.com/postgrespro/mamonsu/files/234592/mamonsu.zip)
[ExamplePlugin.zip](https://github.com/postgrespro/mamonsu/files/234610/ExamplePlugin.zip)

**Comment by vadv** [comment]
У меня работает: https://gist.githubusercontent.com/vadv/513c2272ced9ebf19b3e3f40068946f4/raw/5f69789ccf76bf6fa8ce1ab4a3139104ad18f53d/gistfile1.txt

Точно делаете `-c agent.conf` (там где указано, какие плагины хранятся)

**Comment by vadv** [comment]
может есть смысл сделать искать дефолтный конфиг в windows в текущей директории  + agent.conf и для mamonsu.exe ?

**Comment by vadv** [comment]
вообщем не воспроизводиться :)

**Comment by sgrinko** [comment]
Всё проверил.
Действительно проблема в том, что я запускал без параметра -c agent.conf
предполагая, что файл конфигурации найдется в текущем каталоге (привычка виндузятников)
Формирование XML работает.
Можно закрывать issue
