### ISSUE TITLE
Ошибка при импортировании шаблона (zbx 3.0.3)

### ISSUE THREAD

**Issue by laskin82** [postgrespro/mamonsu#37]
Создано: Группа элементов данных "App-PostgresPro-Linux" в "PostgresPro-Linux".
    Создано: Элемент данных "PostgreSQL: streaming replication lag in seconds" в "PostgresPro-Linux".
    Создано: Элемент данных "PostgreSQL: wal write speed" в "PostgresPro-Linux".
    Создано: Элемент данных "PostgreSQL checkpoints: by timeout" в "PostgresPro-Linux".
    Создано: Элемент данных "PostgreSQL checkpoints: required" в "PostgresPro-Linux".
    Создано: Элемент данных "PostgreSQL checkpoint: write time" в "PostgresPro-Linux".
    Создано: Элемент данных "PostgreSQL checkpoint: sync time" в "PostgresPro-Linux".
    Создано: Элемент данных "PostgreSQL bgwriter: buffers written during checkpoints" в "PostgresPro-Linux".
    Создано: Элемент данных "PostgreSQL bgwriter: buffers written" в "PostgresPro-Linux".
    Создано: Элемент данных "PostgreSQL bgwriter: number of bgwriter stopped by max write count" в "PostgresPro-Linux".
    Создано: Элемент данных "PostgreSQL bgwriter: buffers written directly by a backend" в "PostgresPro-Linux".
    Создано: Элемент данных "PostgreSQL bgwriter: times a backend execute its own fsync" в "PostgresPro-Linux".
    Создано: Элемент данных "PostgreSQL bgwriter: buffers allocated" в "PostgresPro-Linux".
    Создано: Элемент данных "Apps: User-space applications" в "PostgresPro-Linux".
    Создано: Элемент данных "Buffers: Block device cache and dirty" в "PostgresPro-Linux".
    Создано: Элемент данных "Swap: Swap space used" в "PostgresPro-Linux".
    Создано: Элемент данных "Cached: Parked file data (file content) cache" в "PostgresPro-Linux".
    Создано: Элемент данных "Free: Wasted memory" в "PostgresPro-Linux".
    Создано: Элемент данных "Slab: Kernel used memory (inode cache)" в "PostgresPro-Linux".
    Создано: Элемент данных "SwapCached: Fetched unmod yet swap pages" в "PostgresPro-Linux".
    Создано: Элемент данных "PageTables: Map bt virtual and physical" в "PostgresPro-Linux".
    Создано: Элемент данных "VMallocUsed: vmaloc() allocated by kernel" в "PostgresPro-Linux".
    Создано: Элемент данных "Committed_AS: Total committed memory" в "PostgresPro-Linux".
    Создано: Элемент данных "Mapped: All mmap()ed pages" в "PostgresPro-Linux".
    Создано: Элемент данных "Active: Memory recently used" в "PostgresPro-Linux".
    Создано: Элемент данных "Inactive: Memory not currently used" в "PostgresPro-Linux".
    Создано: Элемент данных "Processes: in state running" в "PostgresPro-Linux".
    Создано: Элемент данных "Processes: in state blocked" в "PostgresPro-Linux".
    Создано: Элемент данных "Processes: forkrate" в "PostgresPro-Linux".
    Создано: Элемент данных "Count of autovacuum workers" в "PostgresPro-Linux".
    Создано: Элемент данных "PostgreSQL transactions: total" в "PostgresPro-Linux".
    Создано: Элемент данных "PostgreSQL blocks: hit" в "PostgresPro-Linux".
    Создано: Элемент данных "PostgreSQL blocks: read" в "PostgresPro-Linux".
    Создано: Элемент данных "PostgreSQL event: conflicts" в "PostgresPro-Linux".
    Создано: Элемент данных "PostgreSQL event: deadlocks" в "PostgresPro-Linux".
    Создано: Элемент данных "PostgreSQL event: rollbacks" в "PostgresPro-Linux".
    Создано: Элемент данных "PostgreSQL temp: bytes written" в "PostgresPro-Linux".
    Создано: Элемент данных "PostgreSQL temp: files created" в "PostgresPro-Linux".
    Создано: Элемент данных "PostgreSQL tuples: deleted" в "PostgresPro-Linux".
    Создано: Элемент данных "PostgreSQL tuples: fetched" в "PostgresPro-Linux".
    Создано: Элемент данных "PostgreSQL tuples: inserted" в "PostgresPro-Linux".
    Создано: Элемент данных "PostgreSQL tuples: returned" в "PostgresPro-Linux".
    Создано: Элемент данных "PostgreSQL tuples: updated" в "PostgresPro-Linux".
    Создано: Элемент данных "Block devices: read requests" в "PostgresPro-Linux".
    Создано: Элемент данных "Block devices: write requests" в "PostgresPro-Linux".
    Создано: Элемент данных "PostgreSQL: number of total connections" в "PostgresPro-Linux".
    Создано: Элемент данных "PostgreSQL: number of waiting connections" в "PostgresPro-Linux".
    Создано: Элемент данных "PostgreSQL: number of active connections" в "PostgresPro-Linux".
    Создано: Элемент данных "PostgreSQL: number of idle connections" в "PostgresPro-Linux".
    Создано: Элемент данных "PostgreSQL: number of idle in transaction connections" в "PostgresPro-Linux".
    Создано: Элемент данных "PostgreSQL: ping" в "PostgresPro-Linux".
    Создано: Элемент данных "PostgreSQL: service uptime" в "PostgresPro-Linux".
    Создано: Элемент данных "PostgreSQL: cache hit ratio" в "PostgresPro-Linux".
    Создано: Триггер "PostgreSQL streaming lag to high on {HOSTNAME} (value={ITEM.LASTVALUE})" в "PostgresPro-Linux".
    Создано: Триггер "PostgreSQL required checkpoints occurs to frequently on {HOSTNAME}" в "PostgresPro-Linux".
    Создано: Триггер "Process fork-rate to frequently on {HOSTNAME}" в "PostgresPro-Linux".
    Создано: Триггер "PostgreSQL service was restarted on {HOSTNAME} (uptime={ITEM.LASTVALUE})" в "PostgresPro-Linux".
    Создано: Триггер "PostgreSQL cache hit ratio too low on {HOSTNAME} ({ITEM.LASTVALUE})" в "PostgresPro-Linux".
    Обновлено: Триггер "PostgreSQL streaming lag to high on {HOSTNAME} (value={ITEM.LASTVALUE})" в "PostgresPro-Linux".
    Обновлено: Триггер "PostgreSQL required checkpoints occurs to frequently on {HOSTNAME}" в "PostgresPro-Linux".
    Обновлено: Триггер "Process fork-rate to frequently on {HOSTNAME}" в "PostgresPro-Linux".
    Обновлено: Триггер "PostgreSQL service was restarted on {HOSTNAME} (uptime={ITEM.LASTVALUE})" в "PostgresPro-Linux".
    Обновлено: Триггер "PostgreSQL cache hit ratio too low on {HOSTNAME} ({ITEM.LASTVALUE})" в "PostgresPro-Linux".
    Создано: Правило обнаружения "Database discovery" в "PostgresPro-Linux".
    Создано: Правило обнаружения "Block device discovery" в "PostgresPro-Linux".
    Создано: Прототип элементов данных "Database {#DATABASE}: size" в "PostgresPro-Linux".
    Создано: Прототип элементов данных "Max age (datfrozenxid) in: {#DATABASE}" в "PostgresPro-Linux".
    Создано: Прототип элементов данных "Count of bloating tables in database: {#DATABASE}" в "PostgresPro-Linux".
    Создано: Прототип элементов данных "Block device {#BLOCKDEVICE}: utilization" в "PostgresPro-Linux".
    Создано: Прототип элементов данных "Block device {#BLOCKDEVICE}: read operations" в "PostgresPro-Linux".
    Создано: Прототип элементов данных "Block device {#BLOCKDEVICE}: write operations" в "PostgresPro-Linux".
    Более чем один график с именем "PostgreSQL write-ahead log generation speed" у узла сети.

**Comment by vadv** [comment]
Спасибо, пофиксил!
