### ISSUE TITLE
Ошибка в работе плагина - отсылать нотификацию в Zabbix

### ISSUE THREAD

**Issue by sgrinko** [postgrespro/mamonsu#38]
При добавлении новых плагинов, возможна ситуация возникновения ошибок при их работе.
Необходимо информировать в Zabbix об ошибках при сборе метрики.
Сейчас только об ошибке выполняется запись во внутренний лог.

**Comment by vadv** [comment]
вообщем необходима метрика, которая отсылает кол-во ошибок:
1. если не присылалась метрика больше чем N-мин, то проблема (keep alive)
2. если метрика > 0 то проблема

**Comment by sgrinko** [comment]
а вот интересно, еслть ли возможность как-то передавать в zabbix текст к метрике(динамический). Чтобы можно было видеть имя плагина?

**Comment by vadv** [comment]
метрика - текст,
триггерит если текст > ''

**Comment by vadv** [comment]
@sgrinko прошу потестить: https://www.dropbox.com/s/y9a89usoaefbaax/mamonsu.zip?dl=0

**Comment by sgrinko** [comment]
запустил с ошибкой собранный mamonsu (ссылка)
Итог:

Mamonsu: plugin errors
Отметка времени    Значение
31.05.2016 10:15:16 Error counts: 60, last error: Plugin exception [TypeError]: list indices must be integers, not NoneType
....
31.05.2016 09:54:56 Error counts: 13, last error:

Mamonsu: plugin keep alive
Отметка времени Значение
31.05.2016 10:16:07 0
31.05.2016 10:15:07 0
31.05.2016 10:14:06 0
....

то есть что-то не так. Ошибки (текст) фиксируются, но нет инфы где именно в каком месте ошибка.
Триггера не срабатывают

**Comment by vadv** [comment]
@sgrinko попробуй плиз: https://www.dropbox.com/s/ab9rp7biqkdbkof/mamonsu2.zip?dl=0

**Comment by sgrinko** [comment]
ничего не изменилось
[Mamonsu: plugin errors](http://joxi.ru/xAeGdG0I7MzVmy)
[Mamonsu: plugin keep alive](http://joxi.ru/eAOqVq1HQv1Kmo)
[триггеров нет](http://joxi.ru/ZrJVDVytRQVjrj)

**Comment by sgrinko** [comment]
всё работает корректно теперь
