### ISSUE TITLE
what is the role of mamonsu?

### ISSUE THREAD

**Issue by edib** [postgrespro/mamonsu#41]
I dont understand the role of mamonsu. Is it the replacement of zabbix agent or is it the additional service alongside zabbix agent in a client?

**Comment by vadv** [comment]
Hi!
It is a comprehensive solution that solves the problem of monitoring PostgreSQL, I think that should be enough mamonsu for monitoring PostgreSQL.

**Comment by edib** [comment]
I am using zabbix agent to monitor general operating system object and postgresql server too but all postgresql monitoring information pass over zabbix agent to the zabbix server in this scenario. I think mamonsu scenario, only mamonsu is installed pg server then it passes all pg server and operating system information to the zabbix server. what I am trying to ask is that in this case whether should we also install zabbix agent on the client system or mamonsu is enough for all monitoring.

**Comment by gsmol** [comment]
I think for general server monitoring you should use separate tool, mamonsu collects only DB specific metrics  from your system.

**Comment by michaelforge** [comment]
@edib 
There are cases when metrics bulk-sending is needed (from host to zabbix trappers).

Mamonsu can act as a self-sufficient agent for such tasks. 
It's not limited only to DB metrics, as long as you can write own plugins for it, using examples from repo. =)
