### ISSUE TITLE
[Вопрос] Монитоинг нескольких кластеров (экземпляров) на одном сервере

### ISSUE THREAD

**Issue by lefan** [postgrespro/mamonsu#52]
Возможно ли с помощью mamonsu организовать мониторинг нескольких кластеров pg запущенных на одном сервере. Есть подозрение, что будут проблемы с конфликтом item keys в zabbix.

**Comment by vadv** [comment]
На текущий момент это можно решить так: вы заводите в zabbix N-машин (postgresql-5432, postgresql-5433, ..), а на машине, на которой стоит несколько PostgreSQL вы заводите N-сервисов (mamonsu-5432, mamonsu-5433, ..) в котором прописываете [zabbix][client]=postgresql-5432, .... Из минусов - дублирование информации по системе, из плюсов - у вас будет все работать.

**Comment by vadv** [comment]
ну а вообще, я конечно думал об этом, но в продакшене никогда не имел несколько сервисов PostgreSQL на одной машине, поэтому стал реализовывать мульти-pg.
