### ISSUE TITLE
В версии 1.1.0 часть метрик не может быть доставлена в Zabbix (windows)

### ISSUE THREAD

**Issue by sgrinko** [postgrespro/mamonsu#55]
Вот пример из лога (INFO) 
b'{"response":"success","info":"processed: 40; failed: 7; total: 47; seconds spent: 0.000890"}
b'{"response":"success","info":"processed: 43; failed: 8; total: 51; seconds spent: 0.000684"}
b'{"response":"success","info":"processed: 40; failed: 7; total: 47; seconds spent: 0.002738"}
b'{"response":"success","info":"processed: 43; failed: 8; total: 51; seconds spent: 0.001458"}
b'{"response":"success","info":"processed: 24; failed: 7; total: 31; seconds spent: 0.001125"}
b'{"response":"success","info":"processed: 23; failed: 8; total: 31; seconds spent: 0.001013"}
b'{"response":"success","info":"processed: 39; failed: 8; total: 47; seconds spent: 0.002081"}
b'{"response":"success","info":"processed: 39; failed: 8; total: 47; seconds spent: 0.001159"}
b'{"response":"success","info":"processed: 41; failed: 6; total: 47; seconds spent: 0.003028"}
b'{"response":"success","info":"processed: 39; failed: 8; total: 47; seconds spent: 0.001204"}
b'{"response":"success","info":"processed: 44; failed: 7; total: 51; seconds spent: 0.001261"}
приложил полный лог в режиме INFO
[mamonsu.log.zip](https://github.com/postgrespro/mamonsu/files/422724/mamonsu.log.zip)
![graph](https://cloud.githubusercontent.com/assets/10084993/17738925/e68da198-649b-11e6-9ffc-2a98b96ffa4e.jpg)

**Comment by sgrinko** [comment]
Добавляю лог снятый в режиме DEBUG
[mamonsu.log.debug.zip](https://github.com/postgrespro/mamonsu/files/423036/mamonsu.log.debug.zip)

**Comment by vadv** [comment]
@sgrinko можно плиз выгрузить темплейт **из** zabbix?

**Comment by vadv** [comment]
@sgrinko можно зайти на zabbix: Configuration => hosts => <MCHSDB01.devel.ifx> => items, выбрать status: <not supported> и прислать info?

**Comment by vadv** [comment]
@sgrinko разобрался, проверь помогло или нет?

**Comment by vadv** [comment]
если да, то надо релизить срочно-фикс

**Comment by sgrinko** [comment]
Спасибо. Всё работает.
