### ISSUE TITLE
В custom plugin часть метрик не доходит до Zabbix

### ISSUE THREAD

**Issue by sgrinko** [postgrespro/mamonsu#56]
В текущей версии mamonsu 1.1.2 реализовал 2 плагина

LongQueriesCount.py

https://gist.github.com/sgrinko/b9fc858076810f93770e20f33821ca93

SparkmesActivity.py

https://gist.github.com/sgrinko/b2e9dd635a251a57b0de8541b77cb7c5

проблема есть с работой плагина SparkmesActivity.py
часть метрик оканчивающихся на YPrev неходит до zabbix
Пример с метрикой - calls_upd_Yprev
теряется в среднем каждая  2-я минута
08/18/2016 05:24:51 PM	
08/18/2016 05:23:14 PM	
08/18/2016 05:21:15 PM	
08/18/2016 05:19:14 PM	
08/18/2016 05:16:14 PM	
08/18/2016 05:14:14 PM	
08/18/2016 05:12:13 PM	
08/18/2016 05:10:14 PM	
08/18/2016 05:08:13 PM	
08/18/2016 05:06:14 PM	
08/18/2016 05:04:14 PM	
08/18/2016 05:01:13 PM	
08/18/2016 04:59:14 PM	
08/18/2016 04:57:13 PM	
08/18/2016 04:55:14 PM	
08/18/2016 04:53:14 PM	
08/18/2016 04:51:13 PM	
08/18/2016 04:49:13 PM	
08/18/2016 04:47:13 PM	
08/18/2016 04:45:14 PM	
08/18/2016 04:43:13 PM	
08/18/2016 04:41:13 PM	
08/18/2016 04:39:12 PM
из самого кода плагина вызов 
zbx.send('{0}[{1}_Yprev]'.format(zbxkey, key), float(self.Yprev[idx]), delta)
идёт каждую минуту, что видно по печати INFO сообщений
self.log.info('{0}[{1}_Yprev]'.format(zbxkey, key)+str(self.Yprev[idx]))

об ошибках ничего нет, но я вижу вот такой текст в Zabbix для метрики Mamonsu: plugin errors
08/18/2016 05:33:52 PM 
Errors in the last 60 seconds: 15.          Last error:

прикрепил лог в DEBUG режиме.
[mamonsu.log.debug.zip](https://github.com/postgrespro/mamonsu/files/425215/mamonsu.log.debug.zip)

**Comment by vadv** [comment]
Странное поведение zabbix связана с неправильным указаным UNITS в плагине.
