### ISSUE TITLE
Proposal | Make all plugins configurable in terms of enabled\disabled

### ISSUE THREAD

**Issue by tarabanton** [postgrespro/mamonsu#57]
We are using mamonsu as a full-fledged replacement for passive zabbix-agent.
Sometimes we don't have PostgreSQL. Sometimes we don't want to monitor any disks. Etc, etc
It'll be good to make a feature of enabling\disabling plugins in [plugins] config section.

**Comment by vadv** [comment]
Ok, in next release. May be tomorrow ;)

**Comment by vadv** [comment]
@tarabanton in version > 1.3.0 you can disable all default PostgreSQL plugins:

```
[postgres]
enabled = False
```
