### ISSUE TITLE
Русские названия графиков и их позиций при импорте шаблона

### ISSUE THREAD

**Issue by sgrinko** [postgrespro/mamonsu#68]
Когда я делаю импорт через команду 
mamonsu zabbix template export c:\mamonsu\file_tmpl.xml --url http://zabbix-spark.devel.ifx/zabbix
у меня руский текст исковеркан.
Если же этот же шаблон я вручную портирую через UI Zabbix, то всё хорошо.

**Comment by vadv** [comment]
@sgrinko можно прислать template в личку?

**Comment by sgrinko** [comment]
Файл приложил.
[file_tmpl.zip](https://github.com/postgrespro/mamonsu/files/594236/file_tmpl.zip)

**Comment by sgrinko** [comment]
Почему closed ? Это что починено или объяснено как решать ?

**Comment by popov83** [comment]
Попробуйте новую версию.
В Centos 7 шаблон добавился и русские буквы отображались корректно.

sparkmes: время (firm) |   | pgsql.queries.sparkmes[timefirm] |   | 7d | 365d | Zabbix trapper | App-PostgresPro-Win32 | Enabled |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
  |   | sparkmes: время (firm)_Yprev |   | pgsql.queries.sparkmes[timefirm_Yprev] |   | 7d | 365d | Zabbix trapper | App-PostgresPro-Win32 | Enabled |  
  |   | sparkmes: время (ip)
