### ISSUE TITLE
Возможность задания Default конфигурации для сторонних плагинов.

### ISSUE THREAD

**Issue by tarabanton** [postgrespro/mamonsu#69]
Для сторонних плагинов требуется задание конфигурации по-умолчанию.

**Comment by vadv** [comment]
привет! в смысле в проброска в конфиг? да, конечно думал об этом, но не как руки не доходят.

**Comment by tarabanton** [comment]
Да. Мы сделали несколько плагинов для мониторинга разных сервисов, и хотели задать default конфигурацию. В данный момент, при добавлении файла плагина, приходится описывать всю его конфигурацию в agent.conf

**Comment by vadv** [comment]
@tarabanton c 1.8.4: у каждого плагина появился dict(str:str) DEFAULT_CONFIG, именно это значение попадает в конфиг (секция <plugin_klass_name>), читается от туда при запуске или генерации темплейта.

Пример в плагине uptime:
https://github.com/postgrespro/mamonsu/blob/master/mamonsu/plugins/system/linux/uptime.py#L6
это создаст секцию в дефолтном конфиге:
```
[system_uptime]
uptime = 300
```
если изменить на:
```
[system_uptime]
uptime = 800
```
то при генерации темплейта/запуске плагина значение self.plugin_config('uptime'): https://github.com/postgrespro/mamonsu/blob/master/mamonsu/plugins/system/linux/uptime.py#L30 будет '800'

проверь, может будут идеи как сделать лучше?

**Comment by vadv** [comment]
в 1.8.5 пофикшена маленькая проблема. теперь бонусом можно отключать конкретный плагин в конфиге

**Comment by tarabanton** [comment]
Возможно я что-то делаю не так, но не особо получается для сторонних плагинов
`from mamonsu.lib.plugin import Plugin

class DefConfTest(Plugin):
    DEFAULT_CONFIG = {
        'enabled': str(False),
        'url': 'http://127.0.0.1/nginx_status',
        'file': '/var/log/nginx/access.log',
        'username': str(None),
        'password': str(None)
    }

    def run(self, zbx):
        self.log.debug(self.DEFAULT_CONFIG)
        pluginname = self.__class__.__name__.lower()
        self.log.debug('Class name: {}'.format(pluginname))
        self.log.debug('Do we hava default config? {}'.format(self.config.has_plugin_config(pluginname)))`

`[INFO] 2016-10-06 17:46:37,492 - root	-	Import plugin 'defaultconf_test' from module 'plugins'
[INFO] 2016-10-06 17:46:37,513 - root	-	Start mamonsu
[DEBUG] 2016-10-06 17:46:37,515 - DEFCONFTEST	-	{'url': 'http://127.0.0.1/nginx_status', 'username': 'None', 'password': 'None', 'enabled': 'False', 'file': '/var/log/nginx/access.log'}
[DEBUG] 2016-10-06 17:46:37,515 - DEFCONFTEST	-	Class name: defconftest
[DEBUG] 2016-10-06 17:46:37,515 - DEFCONFTEST	-	Do we hava default config? False`

**Comment by vadv** [comment]
```
class DefConfTest(Plugin):
    DEFAULT_CONFIG = {
        'enabled': str(False),
        'url': 'http://127.0.0.1/nginx_status',
        'file': '/var/log/nginx/access.log',
        'username': str(None),
        'password': str(None)
    }

    def run(self, zbx):
        self.log.debug(self.self.plugin_config('url'))

```

**Comment by tarabanton** [comment]
```
from mamonsu.lib.plugin import Plugin

class DefConfTest(Plugin):
    DEFAULT_CONFIG = {
        'enabled': str(False),
        'url': 'http://127.0.0.1/nginx_status',
        'file': '/var/log/nginx/access.log',
        'username': str(None),
        'password': str(None)
    }

    def run(self, zbx):
        self.log.debug(self.plugin_config('url'))
        self.log.debug(self.self.plugin_config('url'))
```

```
[DEBUG] 2016-10-06 18:20:03,413 - DEFCONFTEST	-	None
[ERROR] 2016-10-06 18:20:03,414 - DEFCONFTEST	-	Plugin exception [AttributeError]: 'DefConfTest' object has no attribute 'self'.
[DEBUG] 2016-10-06 18:20:03,414 - DEFCONFTEST	-	Traceback (most recent call last):
  File "/home/tan/work/mamonsu/mamonsu/lib/plugin.py", line 125, in _loop
    self.run(self.sender)
  File "/home/tan/work/mamonsu/dev/plugins/defaultconf_test.py", line 17, in run
    self.log.debug(self.self.plugin_config('url'))
AttributeError: 'DefConfTest' object has no attribute 'self'
```

**Comment by vadv** [comment]
```
vadv ~/Projects/postgrespro/mamonsu $ cat mamonsu/plugins/system/linux/def_conf_test.py
from mamonsu.lib.plugin import Plugin

class DefConfTest(Plugin):

    DEFAULT_CONFIG = {
        'enabled': str(True),
        'url': 'http://127.0.0.1/nginx_status',
        'file': '/var/log/nginx/access.log',
        'username': str(None),
        'password': str(None)
    }

    def run(self, zbx):
        self.log.error(self.plugin_config('url'))
vadv ~/Projects/postgrespro/mamonsu $ python mamonsu.py 
[INFO] 2016-10-06 18:26:11,230 - root	-	Start mamonsu
[ERROR] 2016-10-06 18:26:11,235 - DEFCONFTEST	-	http://127.0.0.1/nginx_status
[INFO] 2016-10-06 18:26:11,236 - AGENTAPI	-	Starting at http://127.0.0.1:10052
```

**Comment by vadv** [comment]
ругань `AttributeError: 'DefConfTest' object has no attribute 'self'` из-за `self.log.debug(self.self.plugin_config('url'))` двойного self

**Comment by tarabanton** [comment]
Ну я взял код который был предложен  в https://github.com/postgrespro/mamonsu/issues/69#issuecomment-251991981 :-)

Я плагины кидаю в директорию объявляемую в секции 
```
[plugins]
; disabled by default
enabled = True
; directory with user plugins
directory = <some_path>/dev/mamonsu/custom_plugins
```

**Comment by vadv** [comment]
@tarabanton спасибо, зафиксил загрузку конфига из внешних плагинов, сейчас тестики допишу и выложу в 1.8.6

**Comment by vadv** [comment]
@tarabanton вообщем получилось так, что я изменил логику по поводу директории с плагинами, потому что старая была плоха:
* для того чтобы экспортнуть новый конфиг нужно указать старый конфиг.  
* нельзя указать несколько директорий.

поэтому сейчас директория с плагинами добавляются через параметры запуска, `-a` или `--add-plugins`:

* экспортнуть конфиг `mamonsu export config FILE.conf -a /etc/mamonsu/plugins`
* экспортнуть темплейт `mamonsu export template FILE.xml -a /etc/mamonsu/plugins`

Пример работы с конфигом:
```python
from mamonsu.lib.plugin import Plugin
class DefConfTest(Plugin):
    DEFAULT_CONFIG = {
        'key': 'value_for_key',
    }
    def run(self, zbx):
        self.log.error(self.plugin_config('key'))
```
если в конфиге переопределить в секции:
```
[defconftest]
key = value_for_key2
```
и указать при запуске путь до этого конфига, то key будет value_for_key2

**Comment by tarabanton** [comment]
Принято. Вытащил код из репозитория.
`/usr/bin/python2.7 /work/mamonsu/mamonsu.py -c /work/mamonsu/dev/agent.conf --add-plugins /work/mamonsu/dev/plugins`
Плагины не подгружаются (стоит loglevel = DEBUG). стандартные system и pgsql плагины отключены

**Comment by vadv** [comment]
@tarabanton от чего отнаследованны классы плагинов? :(

**Comment by tarabanton** [comment]
@vadv 
`from mamonsu.lib.plugin import Plugin`
Код из твоего примера в https://github.com/postgrespro/mamonsu/issues/69#issuecomment-252083085 так же не подгружается.

**Comment by vadv** [comment]
@tarabanton добавил тестов, действительно починил export, сломал загрузку :) пофиксил и добавил тестов, скоро будет

**Comment by vadv** [comment]
@tarabanton возьми последнюю версию

**Comment by tarabanton** [comment]
@vadv работает. Подтверждаю.
Плагины отрабатывают.
Вопрос, как быть тогда с пакетами для различных ОС, в плане импорта user plugins? 
Придётся добавлять опции в init script.
Может оставить секцию user_plugins?  Добавить возможность указывать несколько путей в directory? 
`for plugins_dir in config.fetch('plugins', 'directory').split():`
а далее обрабатывать их наравне с указанными при запуске
```
[plugins]
; disabled by default
enabled = False
; directory with user plugins
directory = <some_path>/custom_plugins
```

**Comment by tarabanton** [comment]
Пока общаемся в рамках этого функционала, при ошибке в плагине не может нормально ругнуться на ошибку:
```
Traceback (most recent call last):
  File "/home/tan/work/mamonsu/mamonsu.py", line 6, in <module>
    start()
  File "/home/tan/work/mamonsu/mamonsu/lib/runner.py", line 71, in start
    cfg = Config(args.config_file, args.plugins_dirs)
  File "/home/tan/work/mamonsu/mamonsu/lib/config.py", line 65, in __init__
    self._load_external_plugins(plugin_directories)
  File "/home/tan/work/mamonsu/mamonsu/lib/config.py", line 119, in _load_external_plugins
    self._load_external_plugins_from_directory(dir)
  File "/home/tan/work/mamonsu/mamonsu/lib/config.py", line 135, in _load_external_plugins_from_directory
    sys.stderr.write('Can\'t load module: %s', e)
TypeError: function takes exactly 1 argument (2 given)
```
`sys.stderr.write('Can\'t load module: %s', e)` заменил на `sys.stderr.write('Can\'t load module: {}'.format(e))`

**Comment by vadv** [comment]
`sys.stderr.write('Can\'t load module: %s', e)` ага, исправлю.

насчет конфига еще думаю. для того чтобы применить дефолтные настройки плагинов нужно уже прочитать конфиг и загрузить его настройки :) вообщем думаю, но скорее всего оставлю эти 2 возможности одновременно

**Comment by vadv** [comment]
@tarabanton в 1.8.8 вернул ключ в конфиге:
```shell
[plugins]
enabled = False
directory = /etc/mamonsu/plugins
```
при этом из консоли можно задать `-a`, '--add-plugins'.

**Comment by vadv** [comment]
@tarabanton протестируй через конфиг - дай отмашку и закрываем

**Comment by tarabanton** [comment]
@vadv не подтягивает плагины через конфиг. Через командную строку - работает

**Comment by vadv** [comment]
ок, отлично
