### ISSUE TITLE
отключения подчастей мониторинга через конфиг

### ISSUE THREAD

**Issue by sgrinko** [postgrespro/mamonsu#71]
нужно добавить в agent.conf возможность отключения подчастей мониторинга.
Сейчас я запускаю мониторинг на 9.5 и постоянно получаю вот такие сообщения:

[ERROR] 2016-10-04 13:11:55,964 - PGWAITSAMPLING - Extension 'pg_wait_sampling' is not installed
и zabbix постоянно сигналит об ошибках в dashboard
Errors in the last 60 seconds: 2.                        Last error:

**Comment by tarabanton** [comment]
Судя по текущему коду, плагин с неподдерживаемым функционалом должен сам отключаться. Так что это скорее баг.

**Comment by sgrinko** [comment]
автоотключения не происходит.
у меня стоит mamonsu (1.8.1-1) stable;
поправь пожалуйста

**Comment by vadv** [comment]
@sgrinko отключение какого-либо плагина - это прописать в конфиге `enabled = False`:

```
vadv ~/Projects/postgrespro/mamonsu $ tail -n 3 /tmp/config
[pgwaitsampling]
enabled = False

vadv ~/Projects/postgrespro/mamonsu $ python mamonsu.py -c /tmp/config
[INFO] 2016-10-11 15:51:55,233 - root   -       Start mamonsu
[INFO] 2016-10-11 15:51:55,245 - AGENTAPI       -       Starting at http://127.0.0.1:10052
^C[INFO] 2016-10-11 15:51:55,696 - root -       Bye bye!
vadv ~/Projects/postgrespro/mamonsu $
```

**Comment by vadv** [comment]
приделал еще один вид exception: PluginExitException, который не вызывает сообщения в zabbix

**Comment by vadv** [comment]
Добавил сообщение при старте плагина

**Comment by sgrinko** [comment]
работает
