### ISSUE TITLE
Мониторинг потоковой репликации на "спокойном сервере"

### ISSUE THREAD

**Issue by dan-aksenov** [postgrespro/mamonsu#72]
Заметил следующее. При неактивности мастера начинают приходить оповещения о лаге.
После установки задания на регулярный апдейт "технологической" таблицы проблема ушла. 
Но нельзя ли решить это каким либо другим образом?

**Comment by vadv** [comment]
я лаг асинхронной репликации всегда проверял обновлением таблицы на мастере, не сделал так, лишь потому, что это слишком нагло бы выглядело :)

**Comment by vadv** [comment]
но прихожу к выводу, что необходимо завести служебную базу в которой просить включать необходимые экстешены, функции с security definer и прочее...

**Comment by vadv** [comment]
это все можно автоматизировать например командой: `mamonsu deploy <DBNAME> -U <user> .... -p  <port> ...`

**Comment by vadv** [comment]
@sgrinko @tarabanton @dan-aksenov что думаете?

**Comment by dan-aksenov** [comment]
Тоже думаю - что это хорошая идея.

**Comment by dan-aksenov** [comment]
В общем продолжается какая-то фигня. настроил heartbeat табличку с поминутным инсертом. данные синхронны на обоих серверах, лаг растет. делаю апдейт на миллион строк. лаг падает вниз и почти сразу опять взлетает. ла в-час-по-чайной-ложке но ростет постоянно.

**Comment by vadv** [comment]
я уже начал писать `mamonsu deploy` и fallback без него. плюсом от `mamonsu deploy` будет то, что теперь не нужно будет пускать superuser в базу для мониторинга

**Comment by tarabanton** [comment]
@vadv, да, это будет оптимальным выходом. На основную БД все эти экстеншены подключать не вариант

**Comment by tarabanton** [comment]
@vadv может реализовать через функции https://github.com/postgrespro/mamonsu/issues/31 ?

**Comment by vadv** [comment]
тестирую на клиенте версию 1.9.4

**Comment by vadv** [comment]
вообщем для деплоя:

```
# create user and database
su postgres -c 'createdb mamonsu'
su postgres -c 'createuser -a -d -E mamonsu'

# deploy ddl
mamonsu deploy -U postgres -d mamonsu

# set postgres connection config
cat <<EOF > /etc/mamonsu/agent.conf
[postgres]
user = mamonsu
database = mamonsu
EOF
```

И дальше как обычно, при чем `mamonsu` проверяет, установлен этот ddl или нет, если не установлен то дергает fallback-функции

**Comment by vadv** [comment]
@dan-aksenov  просьба протестировать ^^^^

**Comment by dan-aksenov** [comment]
ок. но уже в понедельник.

**Comment by vadv** [comment]
1.9.6: фиксанул багов и переименовал `mamonsu deploy` в `mamonsu bootstrap`

**Comment by sgrinko** [comment]
Создать свою служебную БД - хорошая идея. Я поддерживаю. в #31 issue я предлагал использовать свои функции, но с точки зрения изолированности использовать свою БД ещё лучше. Поддерживаю. В понедельник загружу новую сборку для тестов...

**Comment by vadv** [comment]
на текущий момент поддерживается и старый способ и новый, если mamonsu забутстраплен - используется функция с security definer, если нет - то просто дергается прямой вызов: https://github.com/postgrespro/mamonsu/blob/master/mamonsu/plugins/pgsql/pool.py#L10

**Comment by dan-aksenov** [comment]
Поставил, настроил. Рост лага прекратился, но график теперь кажет сначала 40 секунд, потом 10. А в течении последнего часа медленный спад с 10 до 8 секунд. Хотя, думаю этим можно пренебречь. В любом случае нужно понаблюдать его поведение в течении дня.

**Comment by vadv** [comment]
@dan-aksenov все что меньше 60 секунд - не настоящий лаг, у вас же проверка на мастере и слейве не синхронизирована по времени.

**Comment by dan-aksenov** [comment]
да. я тоже так подумал

**Comment by vadv** [comment]
на самом деле еще все зависит от того, насколько время синхронизировано.
