### ISSUE TITLE
oldest xid, oldest query

### ISSUE THREAD

**Issue by gsmol** [postgrespro/mamonsu#73]
Было бы круто видеть номер самой старой открытой транзакции и дельту с current xid

**Comment by vadv** [comment]
а номера нет, есть только age()

**Comment by gsmol** [comment]
Ок, тогда было бы круто:
1. видеть age самой старой транзакции
2. время выполнения этой самой транзакции

**Comment by vadv** [comment]
правильно ли  я понял что:
```
select greatest(max(age(backend_xmin)), max(age(backend_xid))) from pg_catalog.pg_stat_activity ;
 greatest
----------
       11
(1 row)
```

**Comment by vadv** [comment]
а 2 никак не связано с 1, это:

```
postgres=# select extract(second from max(now() - query_start)) from pg_catalog.pg_stat_activity;
 date_part
-----------
 54.603697
(1 row)
```

**Comment by gsmol** [comment]
почему не xact_start?

**Comment by vadv** [comment]
xact_start:
```
Время начала текущей транзакции в этом процессе или null при отсутствии активной транзакции. Если текущий запрос был первым в своей транзакции, то значение в этом столбце совпадает со значением столбца query_start.
```

**Comment by vadv** [comment]
query_start:

Время начала выполнения активного в данный момент запроса, или, если state не active, то время начала выполнения последнего запроса

**Comment by gsmol** [comment]
select extract( epoch from max(now() - xact_start)) from pg_catalog.pg_stat_activity;

**Comment by gsmol** [comment]
> 
> 
> правильно ли я понял что 1, это:
> 
> select greatest(max(age(backend_xmin)), max(age(backend_xid))) from pg_catalog.pg_stat_activity ;
>  greatest
> ----------
>        11
> (1 row)
> 
> 
Да

**Comment by vadv** [comment]
done
