### ISSUE TITLE
[3rd-party] Небольшая коллекция плагинов

### ISSUE THREAD

**Issue by tarabanton** [postgrespro/mamonsu#75]
Если кого-либо заинтересует, есть несколько плагинов написанных для внутренних нужд.
Поставляется "как есть". Без каких-либо гарантий.
https://github.com/tarabanton/mamonsu-plugins

**Comment by vadv** [comment]
спасибо!

**Comment by vadv** [comment]
nginx-плагин заценил, хорошего качества. добавлю в описание.

**Comment by vadv** [comment]
когда-нибудь решим и такие проблемы: https://github.com/tarabanton/mamonsu-plugins/blob/master/nginx/nginx-status.py#L123 :)

**Comment by vadv** [comment]
@tarabanton теперь такие штуки: `nginx_http_codes = eval(self.plugin_config('http_codes'))` можно писать так: `nginx_http_codes = self.plugin_config('http_codes', as_json=True)`
