### ISSUE TITLE
Disable CFS    

### ISSUE THREAD

**Issue by dan-aksenov** [postgrespro/mamonsu#77]
How to disable CFS to get fid of following error?

> CFS    -       disable plugin: Disable plugin and exit, because PostgresPro Enterprise Edition is not detected

**Comment by vadv** [comment]
This is information message: `[INFO] 2016-11-24 16:50:35,511 - CFS    -       disable plugin: Disable plugin and exit, because PostgresPro Enterprise Edition is not detected [instance: 'host=/tmp/.s.PGSQL.5432 db=postgres user=postgres port=5432']`.

You want to make it disabled by default? ;)

**Comment by dan-aksenov** [comment]
I belive this is the reason i got spammed with zabbix's "mamonsu plugin error" messages

**Comment by vadv** [comment]
which version are you using?

**Comment by dan-aksenov** [comment]
just git-cloned it half an hour ago

**Comment by vadv** [comment]
can i get command result?:
`mamonsu zabbix item error <HOSTNAME_IN_ZABBIX> --url https://zab.postgrespro.ru/zabbix/ --user <USER> --password <PASSWORD>`

**Comment by dan-aksenov** [comment]
here
```
pgsql.blocks[hit]       Received value [3.9] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]
pgsql.checkpoint[checkpoint_sync_time]  Received value [0.00333333333333] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]
pgsql.checkpoint[write_time]    Received value [0.336666666667] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]
pgsql.transactions[total]       Received value [0.45] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]
pgsql.tuples[fetched]   Received value [0.366666666667] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]
pgsql.tuples[returned]  Received value [91.35] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]
pgsql.tuples[updated]   Received value [0.0166666666667] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]
```
so it looks like its not cfs. if only i knew this command earlier.

**Comment by vadv** [comment]
Try to upgrade template (changes: https://github.com/postgrespro/mamonsu/commit/a53ca4031a526a9ae96377fbb4c4d227b19cec59). I think, that upgrade fix this errors. CFS-plugin successfully working on my production machines with vanilla PostgreSQL.

**Comment by dan-aksenov** [comment]
shure, thank you for you time.
