### ISSUE TITLE
Errors in the last 60 seconds

### ISSUE THREAD

**Issue by ktulkhu** [postgrespro/mamonsu#79]
Добрый день. 
Настроил мониторино с помощью вашей разработки. 
Вроде через все продрался, но есть вопросы. 

1. Периодически срабатывает тригер с сообщением: 
** ZABBIX ** PROBLEM   PG Server : Mamonsu plugin errors on pg_centos. Errors in the last 60 seconds: 2.                        Last error: 

в теле сообщения:
Trigger: Mamonsu plugin errors on pg_centos. Errors in the last 60 seconds: 2.                        Last error: 
Trigger status: PROBLEM
Trigger severity: Average
Trigger URL: 
Item values:
1. Mamonsu: plugin errors (PG Server:mamonsu.plugin.errors[]): Errors in the last 60 seconds: 2.                        Last error: 
2. *UNKNOWN* (*UNKNOWN*:*UNKNOWN*): *UNKNOWN* 3. *UNKNOWN* (*UNKNOWN*:*UNKNOWN*): *UNKNOWN*

в логах mamonsu примерно в это время наблюдается следующее: 
[INFO] 2016-11-30 00:12:47,130 - PGSQL-(host=localhost db=mamonsu user=mamonsu port=5432)       -       Found mamonsu bootstrap
[ERROR] 2016-11-30 00:12:48,751 - ZBX-12.23.34.45:10051       -       Timeout: 3s
[INFO] 2016-11-30 00:12:55,902 - ZBX-12.23.34.45:10051        -       started ...
[INFO] 2016-11-30 00:15:49,477 - PGSQL-(host=localhost db=mamonsu user=mamonsu port=5432)       -       Found mamonsu bootstrap
[INFO] 2016-11-30 00:16:44,753 - HEALTH -       === Keep alive ===
[ERROR] 2016-11-30 00:16:49,439 - ZBX-12.23.34.45:10051       -       Timeout: 3s
[INFO] 2016-11-30 00:16:56,146 - ZBX-12.23.34.45:10051        -       started ...
[INFO] 2016-11-30 00:19:47,504 - PGSQL-(host=localhost db=mamonsu user=mamonsu port=5432)       -       Found mamonsu bootstrap

Я правильно понял, что это была ругань как раз на недоступность (?) сервера Zabbix? Или на что-то другое? Как понять, на что поругался mamonsu?

2. В связи с этим вытекающий вопрос: а где и как сконфигурировать таймаут? В данный момент, как я понимаю, он по-дефолту настроен в 60 секунд? И если в это время произошли какие-то ошибки, то срабатывает триггер? Или все не так? 
Как задать, чтобы, например, при такой ошибке триггер срабатывал только после 3х ошибок? Шаблон Zabbix править? 

3. При установке не совсем понял, что происходит при выполнении такой команды: 
mamonsu bootstrap -U postgres --host=localhost -d mamonsu
нужно ли теперь при каждой перезагрузке выполнять эту команду перед тем, как выполнить 
service mamonsu start
? 
Или это разовая операция и ее нужно выполнять только один раз в процессе настройки? 

4. Настраиваю все это на Linux CentOS 7.2, как правильно добавить в автозагрузку mamonsu?

**Comment by vadv** [comment]
1. > Я правильно понял, что это была ругань как раз на недоступность (?) сервера Zabbix?
тред, который отвечал за отправку сообщения соеденялся более 3 секунд (у ZbxSender Iterval установлен в 2 секунды).

>Или на что-то другое?
отсылается такое сообщение:
'mamonsu.plugin.errors[]', 'Errors in the last 60 seconds: {0}. Last error: {1}'
триггер сообщает, попробую сократить текст, чтобы по умолчанию присылался плагин, который делает ошибки.

2. Как задать, чтобы, например, при такой ошибке триггер срабатывал только после 3х ошибок? 
у меня с отсылкой есть ошибки, если zabbix-сервер находиться на другой стороне планеты :)
не охота сокращать до 3 ошибок подряд, но в приниципе можно подправить. правиться тут: https://github.com/postgrespro/mamonsu/blob/2.2.8/mamonsu/plugins/common/health.py#L46

3. `mamonsu bootstrap -U postgres --host=localhost -d mamonsu`
после этой команды mamonsu может мониторить базу без прав superuser, что мне кажется правильным. superuser нужен для того чтобы иметь доступ к содержимому запросов в pg_stat_activity (когда считаем кол-во автовакуумов) и pg_ls_dir (когда считает кол-во wal-файлов которые хранятся в pg_xlog). выполнять ее нужно один раз.

 4. `sudo chkconfig mamonsu on`

**Comment by ktulkhu** [comment]
Спасибо за оперативный ответ!

1.
> тред, который отвечал за отправку сообщения соеденялся более 3 секунд (у ZbxSender Iterval установлен в 2 секунды).

Я так понимаю, правильнее подкрутить интервал ZbxSerner'а? А как это сделать? 
У меня канал до сервера 2 Mbps, если его нагружают (а его нагружают), то на канале появляются задержки. Так как трафик не приоретизирован, то пинги, служебные сообщения и пр. начинают "подтупливать". Из-за чего и возникают фризы с отправкой (я так подозреваю). Расширить канал нет возможности, настроить QoS - тоже. Поэтому, остается, видимо, играться с интервалами ZbxSender. 
Пока что я в шаблоне этот триггер отключил, но это не правильно, считаю. 

2. 
> после этой команды mamonsu может мониторить базу без прав superuser

извините за ламерские вопросы, только начинаю вникать в PostgreSQL
когда я ставил расширения pg_stat_statements, pg_buffercache, я их ставил под суперюзером postgres. Вот тут мое понимание теряется. Эти расширения ставятся для каждой быз отдельно? или они всегда ставятся в базу postgres? Иными словами, нужно ли мне их установить для базы postgres и для базы mamonsu отдельно для каждой? Или достаточно установить их один раз из под пользователя postgres для базы postgres? 
Получается, пользователь mamonsu может сейчас иметь доступ к статистике базы postgres?

**Comment by vadv** [comment]
1. ок, @gsmol увеличит таймаут
2. эти расширения должны быть включены для базы, к которой подключается mamonsu по умолчанию (секция [postgres] в agent.conf)

**Comment by ktulkhu** [comment]
Вот не дает покоя мне этот 

> тред, который отвечал за отправку сообщения соеденялся более 3 секунд (у ZbxSender Iterval установлен в 2 секунды).

У него механизм работы какой? Пытается отправить в течении какого-то интервала (A), затем, если не удалось, повторяет попытку спустя другой интервал (B) и все это какое-то количество раз (N) пытается повторить до успеха, или просто фиксированное кол-во повторов, после чего считает, что провал отправки? 

Может, правильней не увеличивать интервал (А), а поиграть с параметрами А + B + N? 
Чтобы, как у всех сервисов, например, пытается отправить в течении 3 сек, через 30 сек. повторяет попытку отправки, и так, например, 3 раза. Вот после чего уже засчитывает попытку как провальную? Чтобы он не сразу кричал, что ОШИБКА, ОШИБКА, ВСЕ ПРОПАЛО, а по подобию вышеприведенного алгоритма (вообще было бы идеально, если бы были какие-то параметры настройки этого механизма в конфиге). Или это совсем нереально? 
Не могу поймать, из-за чего у меня происходит сбой отправки, как потраблшутить не могу придумать. Все, что пробовал, не помогает выявить, почему такмя ошибка появляется.. В это время, судя zabbix, канал не особо то и нагружен, как выяснилось.

**Comment by tarabanton** [comment]
Вариант увеличения интервала попыток однозначно не самый лучший.
Т.к. при таком подходе, в случае проблем с каналом до сервера мониторинга (у меня, например, сервера раскиданы по всему земному шару), просто накопится огроооомное количество данных которое по факту и не нужно будет.

Сбой отправки может быть как по вине хоста, так и по вине сервера. Тот же Zabbix-server будучи установленным на Debian иногда почему-то не воспринимает пакеты от FreeBSD машин )))

**Comment by ktulkhu** [comment]
так он данные не копит же, как я понял.. попытался отпавить, и дропнул их.. не?
