### ISSUE TITLE
Временное хранилище метрик

### ISSUE THREAD

**Issue by s200999900** [postgrespro/mamonsu#80]
Доброго времение суток!

Можно ли добавить буферизацию данных перед отправкой zabbix server -у ?
На случай если он будет не доступен и после того как он станет доступен отправить данные из временного буфера. По аналогии как это сделано в zabbix proxy.
Спасибо!

**Comment by vadv** [comment]
Буферизация реализована здесь: https://github.com/postgrespro/mamonsu/blob/master/mamonsu/lib/senders/zbx.py в памяти храниться не более 300 метрик, дольше или больше хранить данные, кмк, в памяти нельзя, для этого нужно реализовать только хранение очереди на диске, но я думаю что если у вас есть дц то у вас там должен стоять свой zabbix proxy.

**Comment by s200999900** [comment]
Спасибо!

Так и есть.
