### ISSUE TITLE
Авторизация по SSL сертификатам в PostgreSQL

### ISSUE THREAD

**Issue by s200999900** [postgrespro/mamonsu#81]
Подскажите пожалуйста, что и где необходимо указать в конфигурационом файле mamonsu, чтобы использовать SSL сертификаты для авторизации в PostgreSQL ?
Поддерживается ли libpq connection sting [Connection Strings](https://www.postgresql.org/docs/9.4/static/libpq-connect.html#LIBPQ-CONNSTRING) 
Спасибо!

**Comment by vadv** [comment]
драйвер, который работает с postgresql реализован на чистом python (для переносимости, немного модифицированный pg8000, например передача application name). на текущий момент работает: https://github.com/postgrespro/mamonsu/blob/2.2.9/mamonsu/plugins/pgsql/driver/pg8000/core.py#L1827
если у вас есть силы или возможность помочь написать авторизацию по ssl, то велком.
В скором будущем выйдет scram-протокол, я пытаюсь его реализовать.

**Comment by s200999900** [comment]
Спасибо!
С программированием у меня не сильно.
