### ISSUE TITLE
Trigger for database ping?

### ISSUE THREAD

**Issue by dan-aksenov** [postgrespro/mamonsu#84]
One of my test databases failed month ago. I discovered it only by zabbix's `More than 100 items having missing data for more than 10 minutes`. I guess we should make trigger for `PostgreSQL: ping` mamonsu item.
Made quick fix for myself with:
`{PostgresPro-Linux2:pgsql.ping[].nodata(1m)}=1`

**Comment by casperr0** [comment]
new trigger pgsql.ping available in latest version https://github.com/postgrespro/mamonsu/releases/tag/2.4.1

**Comment by dan-aksenov** [comment]
I think we can close it.
