### ISSUE TITLE
Postgresql 9.1

### ISSUE THREAD

**Issue by deevil** [postgrespro/mamonsu#85]
Имеется Centos 6 + postgresql 9.1.2-1.1C + zabbix 3 + mamonsu 2.2.9 (rpm из репозитория postgrespro)

В забиксе:
Last error: catch error: (u'ERROR', u'42703', u'column "backend_xmin" does not exist', u'30', u'parse_expr.c', u'766', u'transformColumnRef', u'', u'')

Также ряд других ошибок в логах postgresql и mamonsu (во вложении)
[agent.txt](https://github.com/postgrespro/mamonsu/files/726375/agent.txt)
[postgresql-2017-01-23_024218.txt](https://github.com/postgrespro/mamonsu/files/726376/postgresql-2017-01-23_024218.txt)

Я так догадываюсь что дело в версии postgres - параметров которые ищет mamonsu нет в этой версии.

**Comment by popov83** [comment]
postgresql 9.1 уже не поддерживается

**Comment by deevil** [comment]
2 years later...)
