### ISSUE TITLE
Wrong session count with bootstraped agent.

### ISSUE THREAD

**Issue by dan-aksenov** [postgrespro/mamonsu#86]
Active session count graph always shows 1 active session, even when I run multiple pg_benches against database.

![image](https://cloud.githubusercontent.com/assets/7487159/22370615/5c18cac8-e4a3-11e6-9af4-76182d636cc5.png)

Everyting works fine when mamonsu is logged as superuser.

Some observations:
Activity view when connected as superuser (postgres):
```
postgres=# select datname,state from pg_stat_activity;
   datname   | state
-------------+--------
 mamonsu     | idle
 pgbench_zip | idle
 pgbench     | idle
 postgres    | idle
 postgres    | active
 postgres    | idle
 postgres    | active
 postgres    | active
 postgres    | idle
 postgres    | idle
 postgres    | idle
 postgres    | active
 postgres    | active
```
Activity view when connected as bootstraped mamonsu
```
mamonsu=> select datname,state from pg_stat_activity;
   datname   | state
-------------+--------
 mamonsu     | idle
 pgbench_zip | idle
 pgbench     | idle
 postgres    | idle
 mamonsu     | active
 postgres    |
 postgres    |
 postgres    |
 postgres    |
 postgres    |
 postgres    |
 postgres    |
 postgres    |
```
I guess here's the problem. Mamonsu can't see them as active.

**Comment by dan-aksenov** [comment]
any thoughts on this?

**Comment by popov83** [comment]
please, try new version
