### ISSUE TITLE
backend_xmin и pg_lsn

### ISSUE THREAD

**Issue by iakhmetzyanov** [postgrespro/mamonsu#88]
Прошу описать совместимость версий mamonsu  с PostgreSQL, python и так далее.
Хотелось бы ещё более подробную инструкцию или FAQ.

Разворачивание на centOS 6.4 и PostgreSQL 9.3 не привело к каким либо успехам.

При запуске команды bootstrap сообщает, что тип данных pg_lsn не существует.
Это и понятно, ведь pg_lsn появился только в версии 9.4
Если не делать bootstrap, после запуска mamonsu сыпятся ошибки "колонка backend_xmin не существует". 
Если не делать bootstrap до права суперюзера нужно давать пользователю mamonsu  в системе? Если да, то это ни к чему не привело. 
Получаю такие сообщения:
`[ERROR] 2017-02-17 11:50:23,878 - BGWRITER	-	catch error: ('communication error', error(111, 'Connection refused'))
[INFO] 2017-02-17 11:50:23,878 - BGWRITER	-	hint: enable debug level to full exception trace
[INFO] 2017-02-17 11:50:23,879 - DATABASES	-	started ...
[ERROR] 2017-02-17 11:50:23,880 - CONNECTIONS	-	catch error: ('communication error', error(111, 'Connection refused'))
[INFO] 2017-02-17 11:50:23,880 - CONNECTIONS	-	hint: enable debug level to full exception trace
[ERROR] 2017-02-17 11:50:23,881 - DATABASES	-	catch error: ('communication error', error(111, 'Connection refused'))
`
И такие
`[ERROR] 2017-02-17 11:50:23,865 - ZBX-192.168.0.1:10051	-	On request:
{"data": [{"host": и так далее`

**Comment by vadv** [comment]
приходите на pgconf, или смотрете запись, или просто скачайте презентацию :) на нем будет мастер класс по настройке mamonsu.

**Comment by vitabaks** [comment]
Подключаюсь к вопросу, как отключить метрику с запросом "backend_xmin" на старых версиях PG (иногда они есть :) ?

**Comment by gsmol** [comment]
А какая у Вас версия PG? 9.3?
