### ISSUE TITLE
SUSE Linux Enterprise Server 11SP1, 12SP1 build failed

### ISSUE THREAD

**Issue by Ateist1999** [postgrespro/mamonsu#89]
Both SLES 11SP4 and SLES12SP1 builds failed due to missing python2-devel package.

**Comment by vadv** [comment]
did you have SLES Software Development Kit?

**Comment by Ateist1999** [comment]
Yes, i have. Which packet should i install?

**Comment by Ateist1999** [comment]
Yes, i have. Which packet should i install?

**Comment by popov83** [comment]
python-setuptools and  python
