### ISSUE TITLE
DB lock

### ISSUE THREAD

**Issue by mamashin** [postgrespro/mamonsu#90]
При запущенном агенте и попытке удалить или переименовать существующую БД получаю ошибку, что база занята, выключаю агента - все ок.
Я правильно понимаю, что это нормальное поведение ?

**Comment by tarabanton** [comment]
@mamashin да. Mamonsu держит лок на relations иногда. Решение - отключать всё что связано с измерением размера таблиц и баз.

**Comment by vadv** [comment]
связано с тем, что mamonsu держит персист соедение с базой, а базу нельзя переименовать или удалить, если у нее есть клиенты

**Comment by mamashin** [comment]
спс, примерно об этом и догадывался.

**Comment by mamashin** [comment]
А такой воркэраунд прокатит - я изменяю правило дискавери для баз и задаю там только те которые я точно знаю, что  удалять или переименовывать не буду, а с остальными базами могу делать что угодно.  Сработает ?

**Comment by vadv** [comment]
https://github.com/postgrespro/mamonsu/blob/master/mamonsu/plugins/pgsql/databases.py#L15
можно вот в этот плагин добавить exclude, но пока этого не сделано.

**Comment by mamashin** [comment]
А все же "стандартный" вариант для zabbix с использованием встроенного механизма фильтрации чем плох ?

**Comment by vadv** [comment]
потому что agent не исполняет список активных проверок с zabbix, он сам решает в какую базу лезть :) вы в принципе очевидные вещи говорите, их надо реализовать, но пока не дошли руки. В продуктивной жизне база обычно одна и её не удаляют, ренеймят, разве что в какие-то майнтенс-окна, когда создается план работ в котором отключается мониторинг :(

**Comment by mamashin** [comment]
Продуктивные жизни они ведь у каждого свои - вот например одно не маленькое предприятие где 1С подружили Postgres, там кол-во баз только в продакшене несколько десятков, а при этом есть еще всякие тестовые, временные, "на полчасика" поднятые из бэкапа двух недельной давности и т.д. и т.п. :)

**Comment by vadv** [comment]
в pg нет механизмов для ограничения ресурсов одной из баз, вы делаете не правильно, что держите несколько баз на одном сервере.  

Простой пример: если вы начнете транзакцию на тестоврой базе, но закроете её, на соседеней базе не будет работать вакуум, пока не закончиться эта транзакция: физически будут доступны все изменения с момента начала этой тестовой траназакции.

**Comment by mamashin** [comment]
Ну я бы с удовольствием переселился в тот мир, в котором для каждой БД я мог поднять отдельный сервер, но моя реальность такова, что серверов мы себе можем позволить только два - master и slave и с этом приходится как-то жить :)

**Comment by vadv** [comment]
я почему-то так и думал, что это про 1с :)
да, это особенный случай. я подумаю над exclude, например по маске: игнорить базы с названием по regexp

**Comment by mamashin** [comment]
да, например в нашем случае, все что начинается с ^1c_.* - это прод который никто и никогда удалять или переименовывать не будет и именно их и хотелось бы мониторить.
