### ISSUE TITLE
system_enabled option do not change zabbix template

### ISSUE THREAD

**Issue by deepdivenow** [postgrespro/mamonsu#93]
Изменение наблюдаемых категорий в агенте, никак не влияет на создаваемый zabbix template.

Как повторить проблему:
cat /etc/mamonsu/agent.conf
....
[system]
enabled=False
.....
mamonsu export template /tmp/mPostgres.xml  -c /etc/mamonsu/agent.conf

**Comment by popov83** [comment]
Попробуйте новую версию. Сейчас изменения в конфигурационном файле оказывают влияние на шаблоны и на различные параметры по сбору метрик.
