### ISSUE TITLE
Невозможно удалить базу.

### ISSUE THREAD

**Issue by stepansantalov** [postgrespro/mamonsu#99]
Поскольку mamonsu соединяется со всеми имеющимися базами в кластере, невозможно выполнить DROP DATABASE. Хорошо бы иметь триггерный объект, создание/удаление которого приводило бы к тому, чтобы mamonsu складывало соединение к целевой базе.  

В качестве костыля я набросал скрипт который следит за  наличием базы, при появлении которой он останавливает mamonsu и при удалении, соответственно, запускает. Хорошо бы иметь подобное включенным в состав mamonsu.

**Comment by dan-aksenov** [comment]
Мне хватило этого:
```
select pg_terminate_backend(pid) from pg_stat_activity where datname = "database_to_drop";
drop database "database_to_drop";
```
Mamonsu не успевает переподключиться за секунду)
